#include "RTOParser.h"

#include <QDebug>

namespace ks {
namespace plugins {
namespace kunos {
namespace assettocorsa {

bool RTOParser::load(const QString& path, RTOData& out) {
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) return false;

    QTextStream in(&file);
    out = RTOData();

    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith(';') || line.startsWith('#')) continue;

        if (line.startsWith('[') && line.endsWith(']')) continue;

        int eq = line.indexOf('=');
        if (eq < 0) continue;

        QString key = line.left(eq).trimmed().toUpper();
        QString val = line.mid(eq + 1).trimmed();

        if (key == "CAR") out.carName = val;
        else if (key == "GEARS") out.numGears = val.toInt();
        else if (key == "FINALDRIVE" || key == "FINAL_DRIVE") out.finalDrive = val.toFloat();
        else if (key == "MAXRPM" || key == "MAX_RPM") out.maxRpm = val.toFloat();
        else if (key == "SHIFTRPM" || key == "SHIFT_RPM") out.shiftRpm = val.toFloat();
        else if (key.startsWith("GEAR")) {
            int gearNum = key.mid(4).toInt();
            QStringList parts = val.split(',', Qt::SkipEmptyParts);
            if (parts.size() >= 2) {
                RTOGearRatio gr;
                gr.gear = gearNum;
                gr.ratio = parts[0].toFloat();
                if (parts.size() > 1) gr.rpmDrop = parts[1].toFloat();
                out.gears.append(gr);
            }
        }
    }

    file.close();
    std::sort(out.gears.begin(), out.gears.end(),
              [](const RTOGearRatio& a, const RTOGearRatio& b) { return a.gear < b.gear; });
    return !out.gears.isEmpty();
}

bool RTOParser::save(const QString& path, const RTOData& data) {
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) return false;

    QTextStream out(&file);
    out << "; RTO Gearbox file\n";
    out << "; Generated by ksEditor\n\n";

    out << "[HEADER]\n";
    out << "CAR=" << data.carName << "\n";
    out << "GEARS=" << data.numGears << "\n";
    out << "FINALDRIVE=" << data.finalDrive << "\n";
    out << "MAXRPM=" << data.maxRpm << "\n";
    out << "SHIFTRPM=" << data.shiftRpm << "\n\n";

    out << "[RATIOS]\n";
    for (const auto& g : data.gears) {
        out << "GEAR" << g.gear << "=" << g.ratio << "," << g.rpmDrop << "\n";
    }

    file.close();
    return true;
}

bool RTOParser::validate(const RTOData& data, QString& error) {
    if (data.numGears < 1) {
        error = "Invalid number of gears";
        return false;
    }
    if (data.finalDrive <= 0) {
        error = "Invalid final drive ratio";
        return false;
    }
    if (data.maxRpm <= 0) {
        error = "Invalid max RPM";
        return false;
    }
    if (data.gears.size() != data.numGears) {
        error = QString("Gear count mismatch: %1 defined, %2 expected").arg(data.gears.size()).arg(data.numGears);
        return false;
    }
    for (const auto& g : data.gears) {
        if (g.ratio <= 0) {
            error = QString("Gear %1: invalid ratio").arg(g.gear);
            return false;
        }
    }
    return true;
}

RTOData RTOParser::createDefault(int numGears) {
    RTOData data;
    data.numGears = numGears;
    data.finalDrive = 3.5f;
    data.maxRpm = 8000.0f;
    data.shiftRpm = 7500.0f;
    data.carName = "Default";

    // Typical road car ratios
    float baseRatios[] = {3.5f, 2.2f, 1.5f, 1.1f, 0.9f, 0.75f, 0.65f, 0.55f};
    for (int i = 0; i < numGears && i < 8; ++i) {
        RTOGearRatio gr;
        gr.gear = i + 1;
        gr.ratio = baseRatios[i];
        gr.rpmDrop = (i > 0) ? baseRatios[i-1] / baseRatios[i] : 0.0f;
        data.gears.append(gr);
    }
    return data;
}

float RTOParser::calculateSpeedAtRpm(const RTOData& data, int gear, float rpm, float tireRadius) {
    if (gear < 1 || gear > data.gears.size()) return 0.0f;
    float gearRatio = data.gears[gear - 1].ratio;
    float wheelRpm = rpm / (gearRatio * data.finalDrive);
    float speedMs = wheelRpm * 2.0f * 3.14159f * tireRadius / 60.0f;
    return speedMs * 3.6f; // km/h
}

float RTOParser::calculateRpmAtSpeed(const RTOData& data, int gear, float speedKmh, float tireRadius) {
    if (gear < 1 || gear > data.gears.size()) return 0.0f;
    float gearRatio = data.gears[gear - 1].ratio;
    float speedMs = speedKmh / 3.6f;
    float wheelRpm = speedMs * 60.0f / (2.0f * 3.14159f * tireRadius);
    return wheelRpm * gearRatio * data.finalDrive;
}

} // namespace assettocorsa
} // namespace kunos
} // namespace plugins
} // namespace ks