#include "CADParser.h"
#include "CADFormatDetector.h"
#include "CADSTLParser.h"
#include "CADOBJParser.h"
#include "CADAdvancedParsers.h"
#include "../sys/LogManager.h"

namespace CAD {

QString Parser::m_lastError;

bool Parser::read(const QString& filePath, File& outFile)
{
    QString format = FormatDetector::detectFormat(filePath);
    
    LOG_INFO("CADParser", QString("Detected format: %1 for file: %2").arg(format, filePath));
    
    if (format == "STL") {
        return STLParser::parse(filePath, outFile);
    } else if (format == "OBJ") {
        ks::CADOBJParser objParser;
        if (!objParser.loadFromFile(filePath.toStdString())) {
            m_lastError = "Failed to parse OBJ file";
            return false;
        }
        const auto& scene = objParser.scene();
        outFile.format = "OBJ";
        outFile.sourceFile = filePath;
        outFile.assembly.name = QFileInfo(filePath).baseName();

        Solid solid;
        solid.name = QFileInfo(filePath).baseName();
        solid.type = SolidType::BrepSolid;

        QMap<std::string, int> vertexIndexMap;
        int globalVertexOffset = 0;

        for (const auto& objMesh : scene.meshes) {
            int meshVertexOffset = globalVertexOffset;
            for (const auto& v : objMesh.vertices) {
                Point3D p(v.x, v.y, v.z);
                solid.vertices.append(p);
                solid.tessellatedVertices.append(Vector3(v.x, v.y, v.z));
                globalVertexOffset++;
            }
            for (const auto& tri : objMesh.indices) {
                QVector<int> poly;
                poly.append(static_cast<int>(tri.x) + meshVertexOffset);
                poly.append(static_cast<int>(tri.y) + meshVertexOffset);
                poly.append(static_cast<int>(tri.z) + meshVertexOffset);
                solid.tessellatedPolygons.append(poly);
            }
        }

        solid.leftOperand = nullptr;
        solid.rightOperand = nullptr;
        solid.tessellationQuality = 1.0f;

        outFile.assembly.rootComponent.solids.append(solid);
        outFile.faceCount = solid.tessellatedPolygons.size();
        outFile.vertexCount = solid.vertices.size();
        outFile.solidCount = 1;
        outFile.edgeCount = 0;

        LOG_INFO("CADParser", QString("Converted OBJ to CAD::File: %1 faces, %2 vertices")
            .arg(outFile.faceCount).arg(outFile.vertexCount));
        return true;
    } else if (format == "STEP") {
        return STEPParser::parse(filePath, outFile);
    } else if (format == "IGES") {
        return IGESParser::parse(filePath, outFile);
    } else if (format == "DXF") {
        return DXFParser::parse(filePath, outFile);
    } else if (format == "BREP") {
        return BREPParser::parse(filePath, outFile);
    }
    
    m_lastError = QString("Unsupported CAD format: %1").arg(format);
    LOG_ERROR("CADParser", m_lastError);
    return false;
}

bool Parser::write(const QString& filePath, const File& file)
{
    QFile fileOut(filePath);
    if (!fileOut.open(QIODevice::WriteOnly | QIODevice::Text)) {
        m_lastError = QString("Failed to create file: %1").arg(filePath);
        LOG_ERROR("CADParser", m_lastError);
        return false;
    }
    
    QTextStream stream(&fileOut);
    
    // Write STEP header (default output format)
    stream << "ISO-10303-21;\n";
    stream << "HEADER;\n";
    stream << "FILE_DESCRIPTION(('Generated by CAD Parser'), '2;1');\n";
    stream << "FILE_NAME('" << QFileInfo(filePath).fileName() << "', '"
           << QDateTime::currentDateTime().toString(Qt::ISODate) << "', ('Author'), "
           << "('Organization'), 'CAD Parser', 'CAD Parser', '');\n";
    stream << "FILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'));\n";
    stream << "ENDSEC;\n";
    stream << "DATA;\n";
    
    // Write geometry entities (simplified)
    
    stream << "ENDSEC;\n";
    stream << "END-ISO-10303-21;\n";
    
    fileOut.close();
    
    LOG_INFO("CADParser", QString("Saved CAD file: %1").arg(filePath));
    return true;
}

bool Parser::isValid(const QString& filePath)
{
    return FormatDetector::isValid(filePath);
}

QString Parser::getLastError()
{
    return m_lastError;
}

} // namespace CAD
