#include "MaterialFormatParser.h"
#include <QFile>
#include <QTextStream>
#include <QRegularExpression>

namespace ks {

QString MaterialFormatParser::s_lastError;

bool MaterialFormatParser::load(const QString& filePath, MTLFile& outFile)
{
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        s_lastError = "Cannot open file: " + filePath;
        return false;
    }

    QTextStream stream(&file);
    QString content = stream.readAll();
    file.close();

    outFile.sourcePath = filePath;
    return loadFromString(content, outFile);
}

bool MaterialFormatParser::loadFromString(const QString& content, MTLFile& outFile)
{
    QStringList lines = content.split('\n');
    MTLMaterial* currentMat = nullptr;

    for (const QString& rawLine : lines) {
        QString line = rawLine.trimmed();
        if (line.isEmpty() || line.startsWith('#')) continue;

        QStringList parts = line.split(QRegularExpression("\\s+"), Qt::SkipEmptyParts);
        if (parts.isEmpty()) continue;

        QString cmd = parts[0];

        if (cmd == "newmtl") {
            if (parts.size() >= 2) {
                QString matName = parts.mid(1).join(' ');
                outFile.materials[matName] = MTLMaterial();
                outFile.materials[matName].name = matName;
                currentMat = &outFile.materials[matName];
            }
        } else if (currentMat) {
            auto parseFloat3 = [&](float* dst) {
                if (parts.size() >= 4) {
                    dst[0] = parts[1].toFloat();
                    dst[1] = parts[2].toFloat();
                    dst[2] = parts[3].toFloat();
                }
            };
            auto parseFloat = [&](float* dst) {
                if (parts.size() >= 2) *dst = parts[1].toFloat();
            };
            auto parseTexture = [&](QString& dst) {
                if (parts.size() >= 2) dst = parts.mid(1).join(' ');
            };

            if (cmd == "Ka") parseFloat3(currentMat->Ka);
            else if (cmd == "Kd") parseFloat3(currentMat->Kd);
            else if (cmd == "Ks") parseFloat3(currentMat->Ks);
            else if (cmd == "Ke") parseFloat3(currentMat->Ke);
            else if (cmd == "Ns") parseFloat(&currentMat->Ns);
            else if (cmd == "Ni") parseFloat(&currentMat->Ni);
            else if (cmd == "d") parseFloat(&currentMat->d);
            else if (cmd == "Tr") parseFloat(&currentMat->Tr);
            else if (cmd == "illum") { if (parts.size() >= 2) currentMat->illum = parts[1].toInt(); }
            else if (cmd == "map_Ka") parseTexture(currentMat->mapKa);
            else if (cmd == "map_Kd") parseTexture(currentMat->mapKd);
            else if (cmd == "map_Ks") parseTexture(currentMat->mapKs);
            else if (cmd == "map_Ns") parseTexture(currentMat->mapNs);
            else if (cmd == "map_d") parseTexture(currentMat->mapD);
            else if (cmd == "map_bump" || cmd == "bump") parseTexture(currentMat->mapBump);
            else if (cmd == "map_disp" || cmd == "disp") parseTexture(currentMat->mapDisp);
            else if (cmd == "map_refl" || cmd == "refl") parseTexture(currentMat->mapRefl);
            else if (cmd == "map_Ke") parseTexture(currentMat->mapKe);
            else if (cmd == "norm" || cmd == "map_Norm") parseTexture(currentMat->mapNorm);
            else {
                // Custom property
                currentMat->customProperties[cmd] = parts.mid(1).join(' ');
            }
        }
    }

    return !outFile.materials.isEmpty();
}

bool MaterialFormatParser::save(const QString& filePath, const MTLFile& file)
{
    QFile outFile(filePath);
    if (!outFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        s_lastError = "Cannot write file: " + filePath;
        return false;
    }

    QTextStream stream(&outFile);
    stream << "# Generated by ksEditor MaterialFormatParser\n";

    for (auto it = file.materials.begin(); it != file.materials.end(); ++it) {
        const MTLMaterial& mat = it.value();
        stream << "\nnewmtl " << mat.name << "\n";
        stream << "Ka " << mat.Ka[0] << " " << mat.Ka[1] << " " << mat.Ka[2] << "\n";
        stream << "Kd " << mat.Kd[0] << " " << mat.Kd[1] << " " << mat.Kd[2] << "\n";
        stream << "Ks " << mat.Ks[0] << " " << mat.Ks[1] << " " << mat.Ks[2] << "\n";
        stream << "Ke " << mat.Ke[0] << " " << mat.Ke[1] << " " << mat.Ke[2] << "\n";
        stream << "Ns " << mat.Ns << "\n";
        stream << "Ni " << mat.Ni << "\n";
        stream << "d " << mat.d << "\n";
        stream << "illum " << mat.illum << "\n";

        if (!mat.mapKd.isEmpty()) stream << "map_Kd " << mat.mapKd << "\n";
        if (!mat.mapKs.isEmpty()) stream << "map_Ks " << mat.mapKs << "\n";
        if (!mat.mapKa.isEmpty()) stream << "map_Ka " << mat.mapKa << "\n";
        if (!mat.mapBump.isEmpty()) stream << "map_bump " << mat.mapBump << "\n";
        if (!mat.mapDisp.isEmpty()) stream << "map_disp " << mat.mapDisp << "\n";
        if (!mat.mapRefl.isEmpty()) stream << "map_refl " << mat.mapRefl << "\n";
        if (!mat.mapKe.isEmpty()) stream << "map_Ke " << mat.mapKe << "\n";
        if (!mat.mapNorm.isEmpty()) stream << "norm " << mat.mapNorm << "\n";
        if (!mat.mapNs.isEmpty()) stream << "map_Ns " << mat.mapNs << "\n";
        if (!mat.mapD.isEmpty()) stream << "map_d " << mat.mapD << "\n";

        for (auto cp = mat.customProperties.begin(); cp != mat.customProperties.end(); ++cp) {
            stream << cp.key() << " " << cp.value() << "\n";
        }
    }

    outFile.close();
    return true;
}

} // namespace ks