#include "PaintPhotoshop.h"
#include "PaintPainter.h"
#include <QPainter>
#include <QRandomGenerator>
namespace ks { namespace paint {
QVariantMap CameraRawSettings::toMap() const { return {{"exposure",exposure},{"highlights",highlights},{"shadows",shadows},{"whites",whites},{"blacks",blacks},{"clarity",clarity},{"vibrance",vibrance},{"saturation",saturation},{"temp",temp},{"tint",tint},{"dehaze",dehaze}}; }
void CameraRawSettings::fromMap(const QVariantMap& m){ exposure=m.value("exposure",0).toDouble(); highlights=m.value("highlights",0).toDouble(); shadows=m.value("shadows",0).toDouble(); whites=m.value("whites",0).toDouble(); blacks=m.value("blacks",0).toDouble(); clarity=m.value("clarity",0).toDouble(); vibrance=m.value("vibrance",0).toDouble(); saturation=m.value("saturation",0).toDouble(); temp=m.value("temp",0).toDouble(); tint=m.value("tint",0).toDouble(); dehaze=m.value("dehaze",0).toDouble(); }
int PaintPhotoshopEngine::addAdjustment(AdjustmentType t,const QVariantMap& pr){ AdjustmentLayer a; a.type=t; a.params=pr; a.name=QString("Adj%1").arg(m_adjustments.size()); m_adjustments.append(a); emit changed(); return m_adjustments.size()-1; }
bool PaintPhotoshopEngine::removeAdjustment(int idx){ if(idx<0||idx>=m_adjustments.size()) return false; m_adjustments.removeAt(idx); emit changed(); return true; }
bool PaintPhotoshopEngine::setAdjustmentParams(int idx,const QVariantMap& pr){ if(idx<0||idx>=m_adjustments.size()) return false; m_adjustments[idx].params=pr; emit changed(); return true; }
QVariantMap PaintPhotoshopEngine::adjustmentParams(int idx) const{ if(idx<0||idx>=m_adjustments.size()) return {}; return m_adjustments[idx].params; }
QImage PaintPhotoshopEngine::applyAdjustments(const QImage& src) const{ QImage out=src.convertToFormat(QImage::Format_ARGB32); for(auto &a:m_adjustments){ if(!a.enabled) continue; QString key; switch(a.type){ case AdjustmentType::Levels: key="levels"; break; case AdjustmentType::Curves: key="curves"; break; case AdjustmentType::BrightnessContrast: key="brightness"; break; case AdjustmentType::HueSaturation: key="brightness"; break; case AdjustmentType::Invert: out.invertPixels(); continue; case AdjustmentType::Threshold: { int t=a.params.value("threshold",128).toInt(); for(int y=0;y<out.height();++y){ QRgb* l=reinterpret_cast<QRgb*>(out.scanLine(y)); for(int x=0;x<out.width();++x){ int g=qGray(l[x]); l[x]= g>t? qRgba(255,255,255,255):qRgba(0,0,0,255);} } continue; } default: key="brightness"; break; } out=PaintPainter::applyFilter(out,key,a.params); } return out; }
bool PaintPhotoshopEngine::removeLayerEffect(int l,int e){ if(!m_styles.contains(l)||e<0||e>=m_styles[l].effects.size()) return false; m_styles[l].effects.removeAt(e); emit changed(); return true; }
QImage PaintPhotoshopEngine::applyLayerStyle(const QImage& src,int layerIdx,const QSize& doc) const{ if(!m_styles.contains(layerIdx)) return src; auto st=m_styles[layerIdx]; if(!st.visible) return src; QImage out=src; for(auto &eff:st.effects){ if(!eff.enabled) continue; if(eff.type==LayerEffectType::DropShadow){ int dist=eff.params.value("distance",5).toInt(); int blur=eff.params.value("blur",5).toInt(); QColor col=eff.params.value("color",QColor(0,0,0,128)).value<QColor>(); QImage shadow(doc, QImage::Format_ARGB32); shadow.fill(Qt::transparent); QPainter p(&shadow); p.drawImage(dist,dist,src); p.end(); for(int i=0;i<blur;++i){ QImage tmp=shadow; QPainter pp(&shadow); pp.setOpacity(0.3); pp.drawImage(1,1,tmp); pp.end(); } QPainter pr(&out); pr.drawImage(0,0,shadow); pr.end(); Q_UNUSED(col); } else if(eff.type==LayerEffectType::OuterGlow){ QImage glow=src; PaintPainter::applyFilter(glow,"blur",{{"radius",8}}); QPainter pr(&out); pr.setCompositionMode(QPainter::CompositionMode_Screen); pr.drawImage(0,0,glow); pr.end(); } } return out; }
QString PaintPhotoshopEngine::addSmartObject(const QImage& img,const QString& p){ QString id=QString("so%1").arg(m_smartObjects.size()); SmartObject so; so.id=id; so.source=img; so.filePath=p; m_smartObjects[id]=so; emit changed(); return id; }
bool PaintPhotoshopEngine::updateSmartObject(const QString& id,const QImage& img){ if(!m_smartObjects.contains(id)) return false; m_smartObjects[id].source=img; emit changed(); return true; }
bool PaintPhotoshopEngine::rasterizeSmartObject(const QString& id){ if(!m_smartObjects.contains(id)) return false; emit changed(); return true; }
QImage PaintPhotoshopEngine::contentAwareFill(const QImage& img,const QImage& mask) const{ QImage out=img.convertToFormat(QImage::Format_ARGB32); QImage m=mask.convertToFormat(QImage::Format_ARGB32); for(int y=0;y<out.height();++y){ QRgb* l=reinterpret_cast<QRgb*>(out.scanLine(y)); const QRgb* ml=reinterpret_cast<const QRgb*>(m.constScanLine(y)); for(int x=0;x<out.width();++x){ if(qAlpha(ml[x])>10){ int nx=qBound(0,x+ (QRandomGenerator::global()->bounded(20)-10), out.width()-1); int ny=qBound(0,y+ (QRandomGenerator::global()->bounded(20)-10), out.height()-1); l[x]=img.pixel(nx,ny); } } } return out; }
QImage PaintPhotoshopEngine::contentAwareMove(const QImage& img,const QRect& src,const QPoint& dst) const{ QImage out=img; QImage patch=img.copy(src); QPainter p(&out); p.drawImage(dst,patch); p.setCompositionMode(QPainter::CompositionMode_Source); p.fillRect(src,Qt::transparent); p.end(); return contentAwareFill(out, QImage()); }
QImage PaintPhotoshopEngine::contentAwarePatch(const QImage& img,const QRect& s,const QRect& d) const{ QImage out=img; QImage patch=img.copy(s); QPainter p(&out); p.drawImage(d.topLeft(),patch); p.end(); return out; }
QImage PaintPhotoshopEngine::puppetWarp(const QImage& img,const QVector<QPointF>&,const QVector<QPointF>&) const{ return img; }
QImage PaintPhotoshopEngine::liquify(const QImage& img,const QPoint& c,float r,float s,int) const{ QImage out=img.convertToFormat(QImage::Format_ARGB32); int rad=int(r); for(int y=c.y()-rad;y<=c.y()+rad;++y) for(int x=c.x()-rad;x<=c.x()+rad;++x){ if(x<0||y<0||x>=out.width()||y>=out.height()) continue; float d=sqrt(float((x-c.x())*(x-c.x())+(y-c.y())*(y-c.y()))); if(d>rad) continue; float f=(1-d/rad)*s*0.02f; int nx=int(x+f*(QRandomGenerator::global()->bounded(10)-5)); int ny=int(y+f*(QRandomGenerator::global()->bounded(10)-5)); nx=qBound(0,nx,out.width()-1); ny=qBound(0,ny,out.height()-1); out.setPixel(x,y,img.pixel(nx,ny)); } return out; }
QImage PaintPhotoshopEngine::vanishingPoint(const QImage& img,const QVector<QPointF>&) const{ return img; }
QImage PaintPhotoshopEngine::perspectiveWarp(const QImage& img,const QVector<QPointF>&,const QVector<QPointF>&) const{ return img; }
QImage PaintPhotoshopEngine::cameraRawFilter(const QImage& img,const CameraRawSettings& s) const{ QImage out=img.convertToFormat(QImage::Format_ARGB32); double expF=pow(2,s.exposure); for(int y=0;y<out.height();++y){ QRgb* l=reinterpret_cast<QRgb*>(out.scanLine(y)); for(int x=0;x<out.width();++x){ int r=qBound(0,int(qRed(l[x])*expF + s.brightness()),255); int g=qBound(0,int(qGreen(l[x])*expF),255); int b=qBound(0,int(qBlue(l[x])*expF),255); r=qBound(0,int(r + s.highlights*0.5 + s.shadows*0.3 + s.whites*0.2 - s.blacks*0.2),255); l[x]=qRgba(r,g,b,qAlpha(l[x])); } } if(s.clarity!=0) { QImage tmp=out; PaintPainter::applyFilter(tmp,"sharpen",{{"amount",int(s.clarity)}}); out=tmp; } return out; }
QImage PaintPhotoshopEngine::neuralFilter(const QImage& img,const QString&,const QVariantMap&) const{ return img; }
QImage PaintPhotoshopEngine::selectSubject(const QImage& img) const{ QImage m(img.size(), QImage::Format_ARGB32); m.fill(Qt::transparent); QPainter p(&m); p.fillRect(img.rect().adjusted(img.width()/4,img.height()/4,-img.width()/4,-img.height()/4), QColor(0,0,0,255)); p.end(); return m; }
QImage PaintPhotoshopEngine::quickSelection(const QImage& img,const QPoint& seed,float tol) const{ QImage mask(img.size(), QImage::Format_ARGB32); mask.fill(Qt::transparent); if(!img.rect().contains(seed)) return mask; QColor target=img.pixelColor(seed); QVector<QPoint> stack; stack.append(seed); QImage visited(img.size(), QImage::Format_Grayscale8); visited.fill(0); int ti=int(tol); while(!stack.isEmpty()){ QPoint pt=stack.takeLast(); if(pt.x()<0||pt.y()<0||pt.x()>=img.width()||pt.y()>=img.height()) continue; if(visited.pixel(pt.x(),pt.y())) continue; visited.setPixel(pt.x(),pt.y(),1); QColor c=img.pixelColor(pt.x(),pt.y()); if(qAbs(c.red()-target.red())>ti || qAbs(c.green()-target.green())>ti || qAbs(c.blue()-target.blue())>ti) continue; mask.setPixelColor(pt.x(),pt.y(),QColor(255,255,255,255)); stack.append(QPoint(pt.x()+1,pt.y())); stack.append(QPoint(pt.x()-1,pt.y())); stack.append(QPoint(pt.x(),pt.y()+1)); stack.append(QPoint(pt.x(),pt.y()-1)); } return mask; }
QImage PaintPhotoshopEngine::objectSelection(const QImage& img,const QRect& roi) const{ QImage m(img.size(), QImage::Format_ARGB32); m.fill(Qt::transparent); QPainter p(&m); p.fillRect(roi, QColor(255,255,255,255)); p.end(); return m; }
QImage PaintPhotoshopEngine::skySelection(const QImage& img) const{ QImage m(img.size(), QImage::Format_ARGB32); m.fill(Qt::transparent); for(int y=0;y<img.height()/3;++y) for(int x=0;x<img.width();++x){ QColor c=img.pixelColor(x,y); if(c.blue()>c.red()+20) m.setPixelColor(x,y,QColor(255,255,255,200)); } return m; }
void PaintPhotoshopEngine::pushHistory(const QImage& img,const QString& n){ if(m_historyIdx+1 < m_history.size()) m_history = m_history.mid(0,m_historyIdx+1); HistoryState s; s.image=img; s.name=n; s.timestamp=QDateTime::currentMSecsSinceEpoch(); m_history.append(s); m_historyIdx=m_history.size()-1; if(m_history.size()>50) { m_history.removeFirst(); m_historyIdx--; } }
QImage PaintPhotoshopEngine::historyUndo(){ if(!canUndoHistory()) return {}; m_historyIdx--; return m_history[m_historyIdx].image; }
QImage PaintPhotoshopEngine::historyRedo(){ if(!canRedoHistory()) return {}; m_historyIdx++; return m_history[m_historyIdx].image; }
void PaintPhotoshopEngine::createSnapshot(const QString& n){ if(m_historyIdx>=0) m_snapshots[n]=m_history[m_historyIdx].image; }
QString PaintPhotoshopEngine::addAction(const QString& n,const QVariantList& steps){ m_actions[n]=steps; emit changed(); return n; }
bool PaintPhotoshopEngine::playAction(const QString& n){ return m_actions.contains(n); }
bool PaintPhotoshopEngine::batchPlay(const QString& a,const QStringList& files,const QString& outDir){ Q_UNUSED(a); Q_UNUSED(files); Q_UNUSED(outDir); return true; }
bool PaintPhotoshopEngine::saveLayerComp(const QString& n,const QVariantMap& st){ m_layerComps[n]=st; emit changed(); return true; }
bool PaintPhotoshopEngine::loadLayerComp(const QString& n){ return m_layerComps.contains(n); }
QVariantMap PaintPhotoshopEngine::artboardProperties(int idx) const{ if(idx<0||idx>=m_artboards.size()) return {}; QVariantMap m; m["rect"]=m_artboards[idx]; return m; }
int PaintPhotoshopEngine::addArtboard(const QRect& r,const QString&){ m_artboards.append(r); return m_artboards.size()-1; }
bool PaintPhotoshopEngine::removeArtboard(int idx){ if(idx<0||idx>=m_artboards.size()) return false; m_artboards.removeAt(idx); return true; }
QImage PaintPhotoshopEngine::applyBrushDynamics(const QImage& dab,float pressure,float tiltX,float tiltY) const{ Q_UNUSED(tiltX); Q_UNUSED(tiltY); QImage out=dab; double sc=1.0 + m_brushDyn.jitter*pressure*0.5; if(sc!=1.0) out=out.scaled(int(out.width()*sc), int(out.height()*sc), Qt::IgnoreAspectRatio, Qt::SmoothTransformation); return out; }
} }
