#include "PaintPhotoshop.h"
#include "PaintPainter.h"
#include <QPainter>
#include <QRandomGenerator>
#include <QDateTime>
#include <QDir>
#include <QBitmap>
#include <QPainterPath>
namespace ks { namespace paint {
QVariantMap CameraRawSettings::toMap() const { return {{"exposure",exposure},{"highlights",highlights},{"shadows",shadows},{"whites",whites},{"blacks",blacks},{"clarity",clarity},{"vibrance",vibrance},{"saturation",saturation},{"temp",temp},{"tint",tint},{"dehaze",dehaze}}; }
void CameraRawSettings::fromMap(const QVariantMap& m){ exposure=m.value("exposure",0).toDouble(); highlights=m.value("highlights",0).toDouble(); shadows=m.value("shadows",0).toDouble(); whites=m.value("whites",0).toDouble(); blacks=m.value("blacks",0).toDouble(); clarity=m.value("clarity",0).toDouble(); vibrance=m.value("vibrance",0).toDouble(); saturation=m.value("saturation",0).toDouble(); temp=m.value("temp",0).toDouble(); tint=m.value("tint",0).toDouble(); dehaze=m.value("dehaze",0).toDouble(); }
int PaintPhotoshopEngine::addAdjustment(AdjustmentType t,const QVariantMap& pr){ AdjustmentLayer a; a.type=t; a.params=pr; a.name=QString("Adj%1").arg(m_adjustments.size()); m_adjustments.append(a); emit changed(); return m_adjustments.size()-1; }
bool PaintPhotoshopEngine::removeAdjustment(int idx){ if(idx<0||idx>=m_adjustments.size()) return false; m_adjustments.removeAt(idx); emit changed(); return true; }
bool PaintPhotoshopEngine::setAdjustmentParams(int idx,const QVariantMap& pr){ if(idx<0||idx>=m_adjustments.size()) return false; m_adjustments[idx].params=pr; emit changed(); return true; }
QVariantMap PaintPhotoshopEngine::adjustmentParams(int idx) const{ if(idx<0||idx>=m_adjustments.size()) return {}; return m_adjustments[idx].params; }
QImage PaintPhotoshopEngine::applyAdjustments(const QImage& src) const{ QImage out=src.convertToFormat(QImage::Format_ARGB32); for(auto &a:m_adjustments){ if(!a.enabled) continue; QString key; switch(a.type){ case AdjustmentType::Levels: key="levels"; break; case AdjustmentType::Curves: key="curves"; break; case AdjustmentType::BrightnessContrast: key="brightness"; break; case AdjustmentType::HueSaturation: key="brightness"; break; case AdjustmentType::Invert: out.invertPixels(); continue; case AdjustmentType::Threshold: { int t=a.params.value("threshold",128).toInt(); for(int y=0;y<out.height();++y){ QRgb* l=reinterpret_cast<QRgb*>(out.scanLine(y)); for(int x=0;x<out.width();++x){ int g=qGray(l[x]); l[x]= g>t? qRgba(255,255,255,255):qRgba(0,0,0,255);} } continue; } default: key="brightness"; break; } out=PaintPainter::applyFilter(out,key,a.params); } return out; }
bool PaintPhotoshopEngine::removeLayerEffect(int l,int e){ if(!m_styles.contains(l)||e<0||e>=m_styles[l].effects.size()) return false; m_styles[l].effects.removeAt(e); emit changed(); return true; }
QImage PaintPhotoshopEngine::applyLayerStyle(const QImage& src,int layerIdx,const QSize& doc) const{ Q_UNUSED(doc); if(!m_styles.contains(layerIdx)) return src; auto st=m_styles[layerIdx]; if(!st.visible) return src; return src; }
QString PaintPhotoshopEngine::addSmartObject(const QImage& img,const QString& p){ QString id=QString("so%1").arg(m_smartObjects.size()); SmartObject so; so.id=id; so.source=img; so.filePath=p; m_smartObjects[id]=so; emit changed(); return id; }
bool PaintPhotoshopEngine::updateSmartObject(const QString& id,const QImage& img){ if(!m_smartObjects.contains(id)) return false; m_smartObjects[id].source=img; emit changed(); return true; }
bool PaintPhotoshopEngine::rasterizeSmartObject(const QString& id){ if(!m_smartObjects.contains(id)) return false; emit changed(); return true; }
QImage PaintPhotoshopEngine::contentAwareFill(const QImage& img,const QImage& mask) const{ QImage out=img.convertToFormat(QImage::Format_ARGB32); QImage m=mask.convertToFormat(QImage::Format_ARGB32); int w=out.width(), h=out.height(); QVector<QPoint> boundary; for(int y=0;y<h;++y){ const QRgb* ml=reinterpret_cast<const QRgb*>(m.constScanLine(y)); for(int x=0;x<w;++x){ if(qAlpha(ml[x])>10){ bool isEdge=false; for(int dy=-1;dy<=1&&!isEdge;++dy) for(int dx=-1;dx<=1&&!isEdge;++dx){ int nx=x+dx, ny=y+dy; if(nx>=0&&ny>=0&&nx<w&&ny<h){ const QRgb* nml=reinterpret_cast<const QRgb*>(m.constScanLine(ny)); if(qAlpha(nml[nx])<=10) isEdge=true; } } if(isEdge) boundary.append(QPoint(x,y)); } } } for(int y=0;y<h;++y){ QRgb* l=reinterpret_cast<QRgb*>(out.scanLine(y)); const QRgb* ml=reinterpret_cast<const QRgb*>(m.constScanLine(y)); for(int x=0;x<w;++x){ if(qAlpha(ml[x])>10){ int bestDist=INT_MAX; QRgb bestColor=qRgba(0,0,0,0); for(auto &bp:boundary){ int d=(bp.x()-x)*(bp.x()-x)+(bp.y()-y)*(bp.y()-y); if(d<bestDist){ bestDist=d; bestColor=img.pixel(bp.x(),bp.y()); } } double f=qBound(0.0, sqrt(double(bestDist))*0.1, 1.0); QRgb nearby=img.pixel(qBound(0,x+QRandomGenerator::global()->bounded(21)-10,w-1), qBound(0,y+QRandomGenerator::global()->bounded(21)-10,h-1)); int r=int(qRed(bestColor)*(1-f)+qRed(nearby)*f); int g=int(qGreen(bestColor)*(1-f)+qGreen(nearby)*f); int b=int(qBlue(bestColor)*(1-f)+qBlue(nearby)*f); l[x]=qRgba(qBound(0,r,255),qBound(0,g,255),qBound(0,b,255),255); } } } return out; }
QImage PaintPhotoshopEngine::contentAwareMove(const QImage& img,const QRect& src,const QPoint& dst) const{ QImage out=img; QImage patch=img.copy(src); QPainter p(&out); p.drawImage(dst,patch); p.setCompositionMode(QPainter::CompositionMode_Source); p.fillRect(src,Qt::transparent); p.end(); return contentAwareFill(out, QImage()); }
QImage PaintPhotoshopEngine::contentAwarePatch(const QImage& img,const QRect& s,const QRect& d) const{ QImage out=img; QImage patch=img.copy(s); QPainter p(&out); p.drawImage(d.topLeft(),patch); p.end(); return out; }
QImage PaintPhotoshopEngine::puppetWarp(const QImage& img,const QVector<QPointF>&,const QVector<QPointF>&) const{ return img; }
QImage PaintPhotoshopEngine::liquify(const QImage& img,const QPoint& c,float r,float s,int mode) const{ QImage out=img.convertToFormat(QImage::Format_ARGB32); int rad=int(r); float strength=s*0.02f; for(int y=c.y()-rad;y<=c.y()+rad;++y) for(int x=c.x()-rad;x<=c.x()+rad;++x){ if(x<0||y<0||x>=out.width()||y>=out.height()) continue; float dx=float(x-c.x()), dy=float(y-c.y()); float dist=sqrt(dx*dx+dy*dy); if(dist>rad||dist<1e-6f) continue; float falloff=1.0f-dist/rad; falloff=falloff*falloff; float fx=0,fy=0; if(mode==0){ fx=-dx*strength*falloff; fy=-dy*strength*falloff; } else if(mode==1){ fx=-dy*strength*falloff; fy=dx*strength*falloff; } else if(mode==2){ fx=dx*strength*falloff*0.5f; fy=dy*strength*falloff*0.5f; } int sx=qBound(0,int(x+fx),out.width()-1); int sy=qBound(0,int(y+fy),out.height()-1); out.setPixel(x,y,img.pixel(sx,sy)); } return out; }
QImage PaintPhotoshopEngine::vanishingPoint(const QImage& img,const QVector<QPointF>&) const{ return img; }
QImage PaintPhotoshopEngine::perspectiveWarp(const QImage& img,const QVector<QPointF>&,const QVector<QPointF>&) const{ return img; }
QImage PaintPhotoshopEngine::cameraRawFilter(const QImage& img,const CameraRawSettings& s) const{ QImage out=img.convertToFormat(QImage::Format_ARGB32); double expF=pow(2,s.exposure); double vibF=1.0+s.vibrance*0.01; double satF=1.0+s.saturation*0.01; for(int y=0;y<out.height();++y){ QRgb* l=reinterpret_cast<QRgb*>(out.scanLine(y)); for(int x=0;x<out.width();++x){ int rv=qRed(l[x]), gv=qGreen(l[x]), bv=qBlue(l[x]); double r=rv*expF, g=gv*expF, b=bv*expF; r+=s.highlights*0.5+s.shadows*0.3+s.whites*0.2-s.blacks*0.2; g+=s.highlights*0.5+s.shadows*0.3+s.whites*0.2-s.blacks*0.2; b+=s.highlights*0.5+s.shadows*0.3+s.whites*0.2-s.blacks*0.2; if(s.temp!=0){ double t=s.temp*0.5; r+=t; b-=t; } if(s.tint!=0){ double ti=s.tint*0.3; g+=ti; } if(s.dehaze!=0){ double d=s.dehaze*0.01; double avg=(r+g+b)/3.0; r=r+(r-avg)*d; g=g+(g-avg)*d; b=b+(b-avg)*d; } double gray=0.299*r+0.587*g+0.114*b; r=gray+(r-gray)*satF; g=gray+(g-gray)*satF; b=gray+(b-gray)*satF; double maxC=qMax(r,qMax(g,b)); double minC=qMin(r,qMin(g,b)); double sat=(maxC-minC)/(maxC+1e-6); r=gray+(r-gray)*(1.0+sat*(vibF-1.0)); g=gray+(g-gray)*(1.0+sat*(vibF-1.0)); b=gray+(b-gray)*(1.0+sat*(vibF-1.0)); l[x]=qRgba(qBound(0,int(r),255),qBound(0,int(g),255),qBound(0,int(b),255),qAlpha(l[x])); } } if(s.clarity!=0) { QImage tmp=out; PaintPainter::applyFilter(tmp,"sharpen",{{"amount",int(s.clarity)}}); out=tmp; } return out; }
QImage PaintPhotoshopEngine::neuralFilter(const QImage& img,const QString&,const QVariantMap&) const{ return img; }
QImage PaintPhotoshopEngine::selectSubject(const QImage& img) const{ QImage m(img.size(), QImage::Format_ARGB32); m.fill(Qt::transparent); QPainter p(&m); p.fillRect(img.rect().adjusted(img.width()/4,img.height()/4,-img.width()/4,-img.height()/4), QColor(0,0,0,255)); p.end(); return m; }
QImage PaintPhotoshopEngine::quickSelection(const QImage& img,const QPoint& seed,float tol) const{ QImage mask(img.size(), QImage::Format_ARGB32); mask.fill(Qt::transparent); if(!img.rect().contains(seed)) return mask; QColor target=img.pixelColor(seed); QVector<QPoint> stack; stack.append(seed); QImage visited(img.size(), QImage::Format_Grayscale8); visited.fill(0); int ti=int(tol); while(!stack.isEmpty()){ QPoint pt=stack.takeLast(); if(pt.x()<0||pt.y()<0||pt.x()>=img.width()||pt.y()>=img.height()) continue; if(visited.pixel(pt.x(),pt.y())) continue; visited.setPixel(pt.x(),pt.y(),1); QColor c=img.pixelColor(pt.x(),pt.y()); if(qAbs(c.red()-target.red())>ti || qAbs(c.green()-target.green())>ti || qAbs(c.blue()-target.blue())>ti) continue; mask.setPixelColor(pt.x(),pt.y(),QColor(255,255,255,255)); stack.append(QPoint(pt.x()+1,pt.y())); stack.append(QPoint(pt.x()-1,pt.y())); stack.append(QPoint(pt.x(),pt.y()+1)); stack.append(QPoint(pt.x(),pt.y()-1)); } return mask; }
QImage PaintPhotoshopEngine::objectSelection(const QImage& img,const QRect& roi) const{ QImage m(img.size(), QImage::Format_ARGB32); m.fill(Qt::transparent); QPainter p(&m); p.fillRect(roi, QColor(255,255,255,255)); p.end(); return m; }
QImage PaintPhotoshopEngine::skySelection(const QImage& img) const{ QImage m(img.size(), QImage::Format_ARGB32); m.fill(Qt::transparent); for(int y=0;y<img.height()/3;++y) for(int x=0;x<img.width();++x){ QColor c=img.pixelColor(x,y); if(c.blue()>c.red()+20) m.setPixelColor(x,y,QColor(255,255,255,200)); } return m; }
void PaintPhotoshopEngine::pushHistory(const QImage& img,const QString& n){ if(m_historyIdx+1 < m_history.size()) m_history = m_history.mid(0,m_historyIdx+1); HistoryState s; s.image=img; s.name=n; s.timestamp=QDateTime::currentMSecsSinceEpoch(); m_history.append(s); m_historyIdx=m_history.size()-1; if(m_history.size()>50) { m_history.removeFirst(); m_historyIdx--; } }
QImage PaintPhotoshopEngine::historyUndo(){ if(!canUndoHistory()) return {}; m_historyIdx--; return m_history[m_historyIdx].image; }
QImage PaintPhotoshopEngine::historyRedo(){ if(!canRedoHistory()) return {}; m_historyIdx++; return m_history[m_historyIdx].image; }
void PaintPhotoshopEngine::createSnapshot(const QString& n){ if(m_historyIdx>=0) m_snapshots[n]=m_history[m_historyIdx].image; }
QString PaintPhotoshopEngine::addAction(const QString& n,const QVariantList& steps){ m_actions[n]=steps; emit changed(); return n; }
bool PaintPhotoshopEngine::playAction(const QString& n){ return m_actions.contains(n); }
bool PaintPhotoshopEngine::batchPlay(const QString& a,const QStringList& files,const QString& outDir){ if(!m_actions.contains(a)||files.isEmpty()) return false; QVariantList steps=m_actions[a]; QDir dir(outDir); if(!dir.exists()) QDir().mkpath(outDir); bool allOk=true; for(auto &fpath:files){ QFile f(fpath); if(!f.open(QIODevice::ReadOnly)) { allOk=false; continue; } QImage img=QImage::fromData(f.readAll()); f.close(); if(img.isNull()) { allOk=false; continue; } img=img.convertToFormat(QImage::Format_ARGB32_Premultiplied); for(auto &step:steps){ QVariantMap m=step.toMap(); QString cmd=m.value("command").toString(); if(cmd=="brightness"){ PaintPainter::applyFilter(img,"brightness",m); } else if(cmd=="contrast"){ PaintPainter::applyFilter(img,"contrast",m); } else if(cmd=="blur"){ PaintPainter::applyFilter(img,"blur",m); } else if(cmd=="sharpen"){ PaintPainter::applyFilter(img,"sharpen",m); } else if(cmd=="invert"){ img.invertPixels(); } else if(cmd=="flipH"){ img=img.mirrored(true,false); } else if(cmd=="flipV"){ img=img.mirrored(false,true); } else if(cmd=="rotate90"){ QTransform t; t.rotate(90); img=img.transformed(t); } else if(cmd=="rotate180"){ QTransform t; t.rotate(180); img=img.transformed(t); } else if(cmd=="rotate270"){ QTransform t; t.rotate(270); img=img.transformed(t); } else if(cmd=="crop"){ QRect r=m.value("rect").toRect(); if(r.isValid()&&r.intersects(img.rect())) img=img.copy(r.intersected(img.rect())); } else if(cmd=="resize"){ int w=m.value("width",img.width()).toInt(); int h=m.value("height",img.height()).toInt(); if(w>0&&h>0) img=img.scaled(w,h,Qt::IgnoreAspectRatio,Qt::SmoothTransformation); } else if(cmd=="levels"){ PaintPainter::applyFilter(img,"levels",m); } else if(cmd=="curves"){ PaintPainter::applyFilter(img,"curves",m); } else if(cmd=="hueSaturation"){ PaintPainter::applyFilter(img,"hueSaturation",m); } } QFileInfo fi(fpath); QString outName=dir.filePath(fi.baseName()+"_processed."+(fi.suffix().isEmpty()?"png":fi.suffix())); allOk &= img.save(outName); } return allOk; }
bool PaintPhotoshopEngine::saveLayerComp(const QString& n,const QVariantMap& st){ m_layerComps[n]=st; emit changed(); return true; }
bool PaintPhotoshopEngine::loadLayerComp(const QString& n){ return m_layerComps.contains(n); }
QVariantMap PaintPhotoshopEngine::artboardProperties(int idx) const{ if(idx<0||idx>=m_artboards.size()) return {}; QVariantMap m; m["rect"]=m_artboards[idx]; return m; }
int PaintPhotoshopEngine::addArtboard(const QRect& r,const QString&){ m_artboards.append(r); return m_artboards.size()-1; }
bool PaintPhotoshopEngine::removeArtboard(int idx){ if(idx<0||idx>=m_artboards.size()) return false; m_artboards.removeAt(idx); return true; }
QImage PaintPhotoshopEngine::applyBrushDynamics(const QImage& dab,float pressure,float tiltX,float tiltY) const{ Q_UNUSED(tiltX); Q_UNUSED(tiltY); QImage out=dab; double sc=1.0 + m_brushDyn.jitter*pressure*0.5; if(sc!=1.0) out=out.scaled(int(out.width()*sc), int(out.height()*sc), Qt::IgnoreAspectRatio, Qt::SmoothTransformation); return out; }
} }
