#pragma once

#include <QString>
#include <QStringList>
#include <QMap>
#include <QFile>
#include <QTextStream>

namespace ks {
namespace plugins {
namespace kunos {
namespace assettocorsa {

/**
 * @file LuaGenerator.h
 * @brief Lua code generator for Assetto Corsa scripts.
 * 
 * Generates:
 * - AC Apps (onStart, onUpdate, onDraw)
 * - Track scripts (onLoad, onUpdate, onDraw)
 * - Car physics scripts (onUpdate with car API)
 * - Post-process filters (onShader, onUpdate)
 * - Background scripts (onLoad, onUpdate)
 * - Helper modules (math, vector, color, etc.)
 */

class LuaGenerator {
public:
    QString code;
    int indentLevel = 0;
    QString indentStr = "  ";

    LuaGenerator() = default;
    explicit LuaGenerator(const QString& indent) : indentStr(indent) {}

    void reset() {
        code.clear();
        indentLevel = 0;
    }

    QString indent() const {
        return indentStr.repeated(indentLevel);
    }

    void write(const QString& line) {
        code += indent() + line + "\n";
    }

    void writeComment(const QString& comment) {
        code += indent() + "-- " + comment + "\n";
    }

    void writeEmpty() {
        code += "\n";
    }

    void writeFunction(const QString& name, const QString& params = "") {
        code += indent() + "function " + name + "(" + params + ")\n";
        indentLevel++;
    }

    void writeEndFunction() {
        indentLevel--;
        code += indent() + "end\n";
    }

    void writeLocal(const QString& var, const QString& value) {
        code += indent() + "local " + var + " = " + value + "\n";
    }

    void writeReturn(const QString& value) {
        code += indent() + "return " + value + "\n";
    }

    void writeIf(const QString& condition) {
        code += indent() + "if " + condition + " then\n";
        indentLevel++;
    }

    void writeBlockStart(const QString& condition) {
        writeIf(condition);
    }

    void writeElseif(const QString& condition) {
        indentLevel--;
        code += indent() + "elseif " + condition + " then\n";
        indentLevel++;
    }

    void writeElse() {
        indentLevel--;
        code += indent() + "else\n";
        indentLevel++;
    }

    void writeEndIf() {
        indentLevel--;
        code += indent() + "end\n";
    }

    void writeFor(const QString& var, const QString& start, const QString& end) {
        code += indent() + "for " + var + " = " + start + ", " + end + " do\n";
        indentLevel++;
    }

    void writeForEach(const QString& var, const QString& list) {
        code += indent() + "for _, " + var + " in pairs(" + list + ") do\n";
        indentLevel++;
    }

    void writeEndFor() {
        indentLevel--;
        code += indent() + "end\n";
    }

    void writeWhile(const QString& condition) {
        code += indent() + "while " + condition + " do\n";
        indentLevel++;
    }

    void writeEndWhile() {
        indentLevel--;
        code += indent() + "end\n";
    }

    void writeTable(const QString& name) {
        code += indent() + name + " = {\n";
        indentLevel++;
    }

    void writeTableKey(const QString& key, const QString& value) {
        code += indent() + "[" + key + "] = " + value + ",\n";
    }

    void writeTableValue(const QString& value) {
        code += indent() + value + ",\n";
    }

    void writeEndTable(bool trailingComma = false) {
        indentLevel--;
        code += indent() + (trailingComma ? "},\n" : "}\n");
    }

    // --- Template generators ---

    static QString generateApp(const QString& appName, const QString& author) {
        LuaGenerator gen;
        gen.writeComment("Assetto Corsa App: " + appName);
        gen.writeComment("Author: " + author);
        gen.writeComment("Generated by ksEditor");
        gen.writeEmpty();

        gen.write("local ac = ac");

        gen.writeFunction("ac.onStart", "");
        gen.writeComment("Called when the app is loaded");
        gen.writeEndFunction();
        gen.writeEmpty();

        gen.writeFunction("ac.onUpdate", "dt");
        gen.writeComment("Called every frame");
        gen.writeEndFunction();
        gen.writeEmpty();

        gen.writeFunction("ac.onDraw", "");
        gen.writeComment("Called every frame for UI rendering");
        gen.writeLocal("ui", "ac");
        gen.writeBlockStart("if ui");
        gen.writeEndIf();
        gen.writeEndFunction();

        return gen.code;
    }

    static QString generateTrackScript(const QString& trackName) {
        LuaGenerator gen;
        gen.writeComment("Assetto Corsa Track Script: " + trackName);
        gen.writeEmpty();
        gen.writeFunction("script.onLoad", "data");
        gen.writeEndFunction();
        gen.writeEmpty();
        gen.writeFunction("script.onUpdate", "dt");
        gen.writeEndFunction();
        gen.writeEmpty();
        gen.writeFunction("script.onDraw", "x, y, w, h");
        gen.writeEndFunction();
        return gen.code;
    }

    static QString generateCarPhysics(const QString& carName) {
        LuaGenerator gen;
        gen.writeComment("Assetto Corsa Car Physics Script: " + carName);
        gen.writeEmpty();
        gen.write("local ac = ac");
        gen.write("local car = ac.getCar(0)");
        gen.writeEmpty();

        gen.writeFunction("script.physics.onUpdate", "dt, carIndex");
        gen.writeLocal("speed", "car:speed()");
        gen.writeLocal("rpm", "car:rpm()");
        gen.writeLocal("gear", "car:gear()");
        gen.writeEndFunction();

        return gen.code;
    }

    static QString generatePostProcessFilter(const QString& filterName) {
        LuaGenerator gen;
        gen.writeComment("Assetto Corsa Post-Process Filter: " + filterName);
        gen.writeEmpty();

        gen.write("local pp = require('pp')");
        gen.write("local tex = pp:shader()");

        gen.writeFunction("filter.onShader", "pipeline, name");
        gen.write("pp:addShader(name, tex)");
        gen.writeEndFunction();

        gen.writeEmpty();

        gen.writeFunction("filter.onUpdate", "dt");
        gen.writeEndFunction();

        return gen.code;
    }

    static QString generateBackground(const QString& name, const QString& skybox) {
        LuaGenerator gen;
        gen.writeComment("Assetto Corsa Background: " + name);
        gen.write("local ac = ac");
        gen.write("local bg = background");
        gen.writeEmpty();

        gen.writeFunction("script.onLoad", "data");
        gen.write("bg:setSkybox('" + skybox + "')");
        gen.writeEndFunction();

        gen.writeEmpty();

        gen.writeFunction("script.onUpdate", "dt");
        gen.writeEndFunction();

        return gen.code;
    }

    static QString generateMathModule() {
        LuaGenerator gen;
        gen.writeComment("Math utilities for AC Lua scripts");
        gen.writeEmpty();

        gen.writeTable("math_utils");
        gen.write("function clamp(v, min, max) return v < min and min or (v > max and max or v) end");
        gen.write("function lerp(a, b, t) return a + (b - a) * clamp(t, 0, 1) end");
        gen.write("function deg2rad(d) return d * math.pi / 180 end");
        gen.write("function rad2deg(r) return r * 180 / math.pi end");
        gen.write("function map(v, inMin, inMax, outMin, outMax) return outMin + (v - inMin) * (outMax - outMin) / (inMax - inMin) end");
        gen.writeEndTable(true);
        return gen.code;
    }

    static QString generateVectorModule() {
        LuaGenerator gen;
        gen.writeComment("Vector utilities for AC Lua scripts");
        gen.writeEmpty();

        gen.writeTable("vec3");
        gen.write("function new(x, y, z) return {x = x or 0, y = y or 0, z = z or 0} end");
        gen.write("function add(a, b) return {x = a.x + b.x, y = a.y + b.y, z = a.z + b.z} end");
        gen.write("function sub(a, b) return {x = a.x - b.x, y = a.y - b.y, z = a.z - b.z} end");
        gen.write("function mul(a, s) return {x = a.x * s, y = a.y * s, z = a.z * s} end");
        gen.write("function dot(a, b) return a.x * b.x + a.y * b.y + a.z * b.z end");
        gen.write("function length(a) return math.sqrt(a.x*a.x + a.y*a.y + a.z*a.z) end");
        gen.write("function normalize(a) local l = length(a) return l > 0 and mul(a, 1/l) or {x=0,y=0,z=0} end");
        gen.write("function distance(a, b) return length(sub(a, b)) end");
        gen.writeEndTable(true);
        return gen.code;
    }

    static QString generateColorModule() {
        LuaGenerator gen;
        gen.writeComment("Color utilities for AC Lua scripts");
        gen.writeEmpty();

        gen.writeTable("color");
        gen.write("function rgb(r, g, b) return {r = r, g = g, b = b} end");
        gen.write("function rgba(r, g, b, a) return {r = r, g = g, b = b, a = a or 1} end");
        gen.write("function hsv(h, s, v) local c = {r=0,g=0,b=0} local i = math.floor(h*6) local f = h*6-i local p = v*(1-s) local q = v*(1-f*s) local t = v*(1-(1-f)*s) if i%6==0 then c.r=v c.g=t c.b=p elseif i%6==1 then c.r=q c.g=v c.b=p elseif i%6==2 then c.r=p c.g=v c.b=t elseif i%6==3 then c.r=p c.g=q c.b=v elseif i%6==4 then c.r=t c.g=p c.b=v else c.r=v c.g=p c.b=q end return c end");
        gen.writeEndTable(true);
        return gen.code;
    }

    static QString generateACModule() {
        LuaGenerator gen;
        gen.writeComment("AC API wrapper - exposes Kunos API to Lua");
        gen.writeEmpty();

        gen.writeTable("ac");
        gen.write("function getCar(index) return ac.internal.getCar(index) end");
        gen.write("function getTrack() return ac.internal.getTrack() end");
        gen.write("function getState() return ac.internal.getState() end");
        gen.write("function log(msg) ac.internal.log(msg) end");
        gen.writeEndTable(true);
        return gen.code;
    }
};

class LuaParser {
public:
    struct ParseResult {
        bool success = false;
        QString error;
        int line = 0;
        QStringList functions;
        QStringList globals;
        QMap<QString, QString> tableKeys;
    };

    static ParseResult parse(const QString& path) {
        ParseResult result;
        QFile file(path);
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
            result.error = "Cannot open file";
            return result;
        }

        QTextStream in(&file);
        int lineNum = 0;
        QString currentFunction;

        while (!in.atEnd()) {
            QString line = in.readLine();
            lineNum++;

            QString trimmed = line.trimmed();
            if (trimmed.isEmpty() || trimmed.startsWith("--")) continue;

            if (trimmed.startsWith("function ")) {
                int start = trimmed.indexOf("function ") + 9;
                int end = trimmed.indexOf("(", start);
                if (end > start) {
                    QString funcName = trimmed.mid(start, end - start).trimmed();
                    result.functions.append(funcName);
                }
            } else if (trimmed.startsWith("local function ")) {
                int start = trimmed.indexOf("local function ") + 15;
                int end = trimmed.indexOf("(", start);
                if (end > start) {
                    QString funcName = trimmed.mid(start, end - start).trimmed();
                    result.functions.append("(local) " + funcName);
                }
            } else if (trimmed.contains(" = ") && !trimmed.contains("==") && !trimmed.contains("~=")) {
                QStringList parts = trimmed.split("=");
                if (parts.size() == 2) {
                    QString var = parts[0].trimmed();
                    if (!var.contains(".") && !var.contains("[")) {
                        result.globals.append(var);
                    }
                }
            }
        }

        file.close();
        result.success = true;
        return result;
    }

    static ParseResult parseString(const QString& code) {
        ParseResult result;
        QStringList lines = code.split('\n');
        int lineNum = 0;

        for (const QString& line : lines) {
            lineNum++;
            QString trimmed = line.trimmed();
            if (trimmed.isEmpty() || trimmed.startsWith("--")) continue;

            if (trimmed.startsWith("function ")) {
                int start = trimmed.indexOf("function ") + 9;
                int end = trimmed.indexOf("(", start);
                if (end > start) {
                    QString funcName = trimmed.mid(start, end - start).trimmed();
                    result.functions.append(funcName);
                }
            } else if (trimmed.startsWith("local function ")) {
                int start = trimmed.indexOf("local function ") + 15;
                int end = trimmed.indexOf("(", start);
                if (end > start) {
                    QString funcName = trimmed.mid(start, end - start).trimmed();
                    result.functions.append("(local) " + funcName);
                }
            } else if (trimmed.contains(" = ") && !trimmed.contains("==") && !trimmed.contains("~=")) {
                QStringList parts = trimmed.split("=");
                if (parts.size() == 2) {
                    QString var = parts[0].trimmed();
                    if (!var.contains(".") && !var.contains("[")) {
                        result.globals.append(var);
                    }
                }
            }
        }

        result.success = true;
        return result;
    }
};

} // namespace assettocorsa
} // namespace kunos
} // namespace plugins
} // namespace ks