#include "CspConfigParser.h"
#include <QFile>
#include <QTextStream>
#include <QFileInfo>
#include <QDir>
#include <QDebug>
#include <QRegularExpression>
#include <QColor>

namespace ks {

CspConfigParser* CspConfigParser::s_instance = nullptr;

CspConfigParser::CspConfigParser(QObject* parent) : QObject(parent) {}

CspConfigParser* CspConfigParser::instance() {
    if (!s_instance) {
        s_instance = new CspConfigParser();
    }
    return s_instance;
}

QVariantMap CspConfigParser::parseIniFile(const QString& path) {
    QVariantMap root;
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return root;

    QTextStream in(&file);
    QString currentSection;
    static QRegularExpression sectionRe(R"(\[([^\]]+)\])");
    static QRegularExpression commentRe(R"(^(;|#).*)");

    while (!in.atEnd()) {
        QString line = in.readLine();

        if (commentRe.match(line).hasMatch())
            continue;

        QRegularExpressionMatch sectionMatch = sectionRe.match(line);
        if (sectionMatch.hasMatch()) {
            currentSection = sectionMatch.captured(1).trimmed();
            if (!root.contains(currentSection))
                root[currentSection] = QVariantMap();
            continue;
        }

        int eq = line.indexOf('=');
        if (eq > 0) {
            QString key = line.left(eq).trimmed();
            QString val = line.mid(eq + 1).trimmed();
            if (val.startsWith('"') && val.endsWith('"'))
                val = val.mid(1, val.size() - 2);
            if (!key.isEmpty()) {
                if (!currentSection.isEmpty()) {
                    QVariantMap section = root[currentSection].toMap();
                    section[key] = val;
                    root[currentSection] = section;
                }
            }
        }
    }

    file.close();
    return root;
}

bool CspConfigParser::writeIniFile(const QString& path, const QVariantMap& sections) {
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;

    QTextStream out(&file);
    out << "; Generated by ksEditor CSP Config Editor\n\n";

    for (auto sectionIt = sections.constBegin(); sectionIt != sections.constEnd(); ++sectionIt) {
        out << "[" << sectionIt.key() << "]\n";
        const QVariant sectionVal = sectionIt.value();
        if (sectionVal.typeId() == QVariant::Map) {
            QVariantMap keys = sectionVal.toMap();
            for (auto keyIt = keys.constBegin(); keyIt != keys.constEnd(); ++keyIt) {
                out << keyIt.key() << "=" << keyIt.value().toString() << "\n";
            }
        }
        out << "\n";
    }

    file.close();
    return true;
}

QVariantMap CspConfigParser::loadCarConfig(const QString& path) {
    return parseIniFile(path);
}

QVariantMap CspConfigParser::loadTrackConfig(const QString& path) {
    return parseIniFile(path);
}

bool CspConfigParser::saveCarConfig(const QString& path, const QVariantMap& data) {
    QDir().mkpath(QFileInfo(path).absolutePath());
    return writeIniFile(path, data);
}

bool CspConfigParser::saveTrackConfig(const QString& path, const QVariantMap& data) {
    QDir().mkpath(QFileInfo(path).absolutePath());
    return writeIniFile(path, data);
}

QVariantList CspConfigParser::parseEmissives(const QVariantMap& sections) {
    QVariantList result;

    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        const QString& sectionName = it.key();
        if (sectionName.startsWith("EMISSIVE") || sectionName.startsWith("EMISSIVE_LIGHT")) {
            QVariantMap section = it.value().toMap();

            CspEmissiveConfig config;
            config.name = section.value("NAME").toString();
            config.meshName = section.value("MESHES").toString();
            config.materialName = section.value("MATERIALS").toString();
            config.color = section.value("COLOR").toString();
            config.colorOff = section.value("OFF_COLOR").toString();
            config.location = section.value("LOCATION").toString();
            config.lag = section.value("LAG", 0.0).toDouble();
            config.simulateHeating = section.value("SIMULATE_HEATING", 0.0).toDouble();
            config.bindToHeadlights = section.value("BIND_TO_HEADLIGHTS", "0").toString() == "1";
            config.active = section.value("ACTIVE", "1").toString() == "1";
            config.condition = section.value("CONDITION").toString();

            QVariantMap map;
            map.insert("name", config.name);
            map.insert("meshName", config.meshName);
            map.insert("color", config.color);
            map.insert("colorOff", config.colorOff);
            map.insert("location", config.location);
            map.insert("lag", config.lag);
            map.insert("simulateHeating", config.simulateHeating);
            map.insert("bindToHeadlights", config.bindToHeadlights);
            map.insert("active", config.active);
            map.insert("condition", config.condition);
            map.insert("sectionName", sectionName);
            result.append(map);
        }
    }
    return result;
}

QVariantList CspConfigParser::parseBrakeDiscs(const QVariantMap& sections) {
    QVariantList result;

    if (sections.contains("BRAKEDISC_FX")) {
        QVariantMap fx = sections.value("BRAKEDISC_FX").toMap();
        QVariantMap disc;
        disc.insert("ambientMult", fx.value("AMBIENT_MULT", "0.6").toDouble());
        disc.insert("reflectionMult", fx.value("REFLECTION_MULT", "1.0").toDouble());
        disc.insert("discInternalRadius", fx.value("DISC_INTERNAL_RADIUS", "0.126").toDouble());
        disc.insert("rimInternalRadius", fx.value("RIM_INTERNAL_RADIUS", "0.06").toDouble());
        disc.insert("position", "all");
        result.append(disc);
    }

    if (sections.contains("BRAKEDISC_FX_FRONT")) {
        QVariantMap fx = sections.value("BRAKEDISC_FX_FRONT").toMap();
        QVariantMap disc;
        disc.insert("ambientMult", fx.value("AMBIENT_MULT", "1.6").toDouble());
        disc.insert("reflectionMult", fx.value("REFLECTION_MULT", "2.0").toDouble());
        disc.insert("discInternalRadius", fx.value("DISC_INTERNAL_RADIUS", "0.105").toDouble());
        disc.insert("rimInternalRadius", fx.value("RIM_INTERNAL_RADIUS", "0.08").toDouble());
        disc.insert("position", "front");
        result.append(disc);
    }

    if (sections.contains("BRAKEDISC_FX_REAR")) {
        QVariantMap fx = sections.value("BRAKEDISC_FX_REAR").toMap();
        QVariantMap disc;
        disc.insert("ambientMult", fx.value("AMBIENT_MULT", "1.6").toDouble());
        disc.insert("reflectionMult", fx.value("REFLECTION_MULT", "2.0").toDouble());
        disc.insert("discInternalRadius", fx.value("DISC_INTERNAL_RADIUS", "0.101").toDouble());
        disc.insert("rimInternalRadius", fx.value("RIM_INTERNAL_RADIUS", "0.08").toDouble());
        disc.insert("position", "rear");
        result.append(disc);
    }

    return result;
}

QVariantList CspConfigParser::parseTrackLights(const QVariantMap& sections) {
    QVariantList result;

    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        const QString& sectionName = it.key();

        if (sectionName.startsWith("LIGHT_SERIES") || sectionName.startsWith("LIGHT_")) {
            if (sectionName == "LIGHTING" || sectionName == "LIGHT_POLLUTION") continue;

            QVariantMap section = it.value().toMap();

            if (section.value("ACTIVE", "1").toString() != "1") continue;

            QVariantMap light;
            light.insert("name", section.value("DESCRIPTION").toString());
            light.insert("meshName", section.value("MESHES").toString());
            light.insert("materialName", section.value("MATERIALS").toString());
            light.insert("position", section.value("POSITION").toString());
            light.insert("direction", section.value("DIRECTION").toString());
            light.insert("color", section.value("COLOR").toString());
            light.insert("colorOff", section.value("COLOR_OFF").toString());
            light.insert("spot", section.value("SPOT", "150").toDouble());
            light.insert("spotSharpness", section.value("SPOT_SHARPNESS", "0.7").toDouble());
            light.insert("range", section.value("RANGE", "20").toDouble());
            light.insert("fadeAt", section.value("FADE_AT", "700").toDouble());
            light.insert("fadeSmooth", section.value("FADE_SMOOTH", "100").toDouble());
            light.insert("condition", section.value("CONDITION").toString());
            light.insert("clusterThreshold", section.value("CLUSTER_THRESHOLD", "10").toInt());
            light.insert("diffuseConcentration", section.value("DIFFUSE_CONCENTRATION", "0.5").toDouble());
            light.insert("specularMult", section.value("SPECULAR_MULT", "1.0").toDouble());
            light.insert("offset", section.value("OFFSET").toString());
            light.insert("sectionName", sectionName);
            result.append(light);
        }
    }
    return result;
}

QVariantList CspConfigParser::parseMaterialAdjustments(const QVariantMap& sections) {
    QVariantList result;

    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        const QString& sectionName = it.key();

        if (sectionName.startsWith("MATERIAL_ADJUSTMENT")) {
            QVariantMap section = it.value().toMap();

            if (section.value("ACTIVE", "1").toString() != "1") continue;

            QVariantMap adjustment;
            adjustment.insert("name", section.value("DESCRIPTION").toString());
            adjustment.insert("meshes", section.value("MESHES").toString());
            adjustment.insert("materials", section.value("MATERIALS").toString());
            adjustment.insert("condition", section.value("CONDITION").toString());
            adjustment.insert("key0", section.value("KEY_0").toString());
            adjustment.insert("value0", section.value("VALUE_0").toString());
            adjustment.insert("value0Off", section.value("VALUE_0_OFF").toString());
            adjustment.insert("key1", section.value("KEY_1").toString());
            adjustment.insert("value1", section.value("VALUE_1").toString());
            adjustment.insert("value1Off", section.value("VALUE_1_OFF").toString());
            adjustment.insert("range", section.value("RANGE", "20").toDouble());
            adjustment.insert("rangeGradientOffset", section.value("RANGE_GRADIENT_OFFSET", "0.2").toDouble());
            adjustment.insert("spot", section.value("SPOT", "75").toDouble());
            adjustment.insert("spotSharpness", section.value("SPOT_SHARPNESS", "0.5").toDouble());
            adjustment.insert("blendMode", section.value("BLEND_MODE").toString());
            adjustment.insert("sectionName", sectionName);
            adjustment.insert("index", result.size());
            result.append(adjustment);
        }
    }
    return result;
}

QVariantList CspConfigParser::parseConditions(const QVariantMap& sections) {
    QVariantList result;

    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        const QString& sectionName = it.key();

        if (sectionName.startsWith("CONDITION")) {
            QVariantMap section = it.value().toMap();

            QVariantMap condition;
            condition.insert("name", section.value("NAME").toString());
            condition.insert("input", section.value("INPUT").toString());
            condition.insert("flashingFrequency", section.value("FLASHING_FREQUENCY", "0").toDouble());
            condition.insert("flashingMinValue", section.value("FLASHING_MIN_VALUE", "0").toDouble());
            condition.insert("flashingNoiseAmplitude", section.value("FLASHING_NOISE_AMPLITUDE", "0").toDouble());
            condition.insert("flashingSkippedOffState", section.value("FLASHING_SKIP_OFF_STATE", "0").toString() == "1");
            condition.insert("flashingSkippedDownhillState", section.value("FLASHING_SKIP_DOWNHILL_STATE", "0").toString() == "1");
            condition.insert("flashingSynced", section.value("FLASHING_SYNCED", "0").toString() == "1");
            condition.insert("flashingSmoothness", section.value("FLASHING_SMOOTHNESS").toString());
            condition.insert("flashingLut", section.value("FLASHING_LUT").toString());
            condition.insert("lag", section.value("LAG", "0").toDouble());
            condition.insert("lagDelayOff", section.value("LAG_DELAY_OFF", "1").toDouble());
            condition.insert("lagDelayOn", section.value("LAG_DELAY_ON", "5").toDouble());
            condition.insert("simulateHeating", section.value("SIMULATE_HEATING", "0").toDouble());
            condition.insert("sectionName", sectionName);
            result.append(condition);
        }
    }
    return result;
}

QVariantMap CspConfigParser::serializeEmissives(const QVariantList& emissives) {
    QVariantMap result;
    for (int i = 0; i < emissives.size(); ++i) {
        QVariantMap e = emissives.at(i).toMap();
        QString sectionName = e.value("sectionName").toString();
        if (sectionName.isEmpty()) {
            sectionName = QString("EMISSIVE_%1").arg(i);
        }
        QVariantMap section;
        if (!e.value("name").toString().isEmpty())
            section.insert("NAME", e.value("name").toString());
        if (!e.value("meshName").toString().isEmpty())
            section.insert("MESHES", e.value("meshName").toString());
        if (!e.value("materialName").toString().isEmpty())
            section.insert("MATERIALS", e.value("materialName").toString());
        if (!e.value("color").toString().isEmpty())
            section.insert("COLOR", e.value("color").toString());
        if (!e.value("colorOff").toString().isEmpty())
            section.insert("OFF_COLOR", e.value("colorOff").toString());
        if (!e.value("location").toString().isEmpty())
            section.insert("LOCATION", e.value("location").toString());
        section.insert("LAG", QString::number(e.value("lag", 0.0).toDouble()));
        section.insert("SIMULATE_HEATING", QString::number(e.value("simulateHeating", 0.0).toDouble()));
        section.insert("BIND_TO_HEADLIGHTS", e.value("bindToHeadlights", false).toBool() ? "1" : "0");
        section.insert("ACTIVE", e.value("active", true).toBool() ? "1" : "0");
        if (!e.value("condition").toString().isEmpty())
            section.insert("CONDITION", e.value("condition").toString());
        result.insert(sectionName, section);
    }
    return result;
}

QVariantMap CspConfigParser::serializeBrakeDiscs(const QVariantList& brakeDiscs) {
    QVariantMap result;
    for (const QVariant& v : brakeDiscs) {
        QVariantMap d = v.toMap();
        QString position = d.value("position").toString();
        QString sectionName;

        if (position == "front") {
            sectionName = "BRAKEDISC_FX_FRONT";
        } else if (position == "rear") {
            sectionName = "BRAKEDISC_FX_REAR";
        } else {
            sectionName = "BRAKEDISC_FX";
        }

        QVariantMap section;
        section.insert("AMBIENT_MULT", QString::number(d.value("ambientMult", 0.6).toDouble()));
        section.insert("REFLECTION_MULT", QString::number(d.value("reflectionMult", 1.0).toDouble()));
        section.insert("DISC_INTERNAL_RADIUS", QString::number(d.value("discInternalRadius", 0.126).toDouble()));
        section.insert("RIM_INTERNAL_RADIUS", QString::number(d.value("rimInternalRadius", 0.06).toDouble()));
        result.insert(sectionName, section);
    }
    return result;
}

QVariantMap CspConfigParser::serializeTrackLights(const QVariantList& trackLights) {
    QVariantMap result;
    for (int i = 0; i < trackLights.size(); ++i) {
        QVariantMap l = trackLights.at(i).toMap();
        QString sectionName = l.value("sectionName").toString();
        if (sectionName.isEmpty()) {
            sectionName = QString("LIGHT_SERIES_%1").arg(i);
        }
        QVariantMap section;
        section.insert("ACTIVE", l.value("active", true).toBool() ? "1" : "0");
        if (!l.value("description").toString().isEmpty())
            section.insert("DESCRIPTION", l.value("description").toString());
        if (!l.value("meshName").toString().isEmpty())
            section.insert("MESHES", l.value("meshName").toString());
        if (!l.value("materialName").toString().isEmpty())
            section.insert("MATERIALS", l.value("materialName").toString());
        if (!l.value("offset").toString().isEmpty())
            section.insert("OFFSET", l.value("offset").toString());
        if (!l.value("direction").toString().isEmpty())
            section.insert("DIRECTION", l.value("direction").toString());
        section.insert("SPOT", QString::number(l.value("spot", 150.0).toDouble()));
        section.insert("SPOT_SHARPNESS", QString::number(l.value("spotSharpness", 0.7).toDouble()));
        section.insert("RANGE", QString::number(l.value("range", 20.0).toDouble()));
        section.insert("FADE_AT", QString::number(l.value("fadeAt", 700.0).toDouble()));
        section.insert("FADE_SMOOTH", QString::number(l.value("fadeSmooth", 100.0).toDouble()));
        section.insert("CLUSTER_THRESHOLD", QString::number(l.value("clusterThreshold", 10).toInt()));
        section.insert("DIFFUSE_CONCENTRATION", QString::number(l.value("diffuseConcentration", 0.5).toDouble()));
        section.insert("SPECULAR_MULT", QString::number(l.value("specularMult", 1.0).toDouble()));
        if (!l.value("color").toString().isEmpty())
            section.insert("COLOR", l.value("color").toString());
        if (!l.value("colorOff").toString().isEmpty())
            section.insert("COLOR_OFF", l.value("colorOff").toString());
        if (!l.value("condition").toString().isEmpty())
            section.insert("CONDITION", l.value("condition").toString());
        result.insert(sectionName, section);
    }
    return result;
}

QVariantMap CspConfigParser::serializeMaterialAdjustments(const QVariantList& adjustments) {
    QVariantMap result;
    for (const QVariant& v : adjustments) {
        QVariantMap a = v.toMap();
        QString sectionName = a.value("sectionName").toString();
        if (sectionName.isEmpty()) {
            int idx = a.value("index", result.size()).toInt();
            sectionName = QString("MATERIAL_ADJUSTMENT_%1").arg(idx);
        }
        QVariantMap section;
        section.insert("ACTIVE", a.value("active", true).toBool() ? "1" : "0");
        if (!a.value("description").toString().isEmpty())
            section.insert("DESCRIPTION", a.value("description").toString());
        if (!a.value("meshes").toString().isEmpty())
            section.insert("MESHES", a.value("meshes").toString());
        if (!a.value("materials").toString().isEmpty())
            section.insert("MATERIALS", a.value("materials").toString());
        if (!a.value("key0").toString().isEmpty())
            section.insert("KEY_0", a.value("key0").toString());
        if (!a.value("value0").toString().isEmpty())
            section.insert("VALUE_0", a.value("value0").toString());
        if (!a.value("value0Off").toString().isEmpty())
            section.insert("VALUE_0_OFF", a.value("value0Off").toString());
        if (!a.value("key1").toString().isEmpty())
            section.insert("KEY_1", a.value("key1").toString());
        if (!a.value("value1").toString().isEmpty())
            section.insert("VALUE_1", a.value("value1").toString());
        if (!a.value("value1Off").toString().isEmpty())
            section.insert("VALUE_1_OFF", a.value("value1Off").toString());
        section.insert("RANGE", QString::number(a.value("range", 20.0).toDouble()));
        section.insert("RANGE_GRADIENT_OFFSET", QString::number(a.value("rangeGradientOffset", 0.2).toDouble()));
        section.insert("SPOT", QString::number(a.value("spot", 75.0).toDouble()));
        section.insert("SPOT_SHARPNESS", QString::number(a.value("spotSharpness", 0.5).toDouble()));
        if (!a.value("blendMode").toString().isEmpty())
            section.insert("BLEND_MODE", a.value("blendMode").toString());
        if (!a.value("condition").toString().isEmpty())
            section.insert("CONDITION", a.value("condition").toString());
        result.insert(sectionName, section);
    }
    return result;
}

QVariantMap CspConfigParser::serializeConditions(const QVariantList& conditions) {
    QVariantMap result;
    for (int i = 0; i < conditions.size(); ++i) {
        QVariantMap c = conditions.at(i).toMap();
        QString sectionName = c.value("sectionName").toString();
        if (sectionName.isEmpty()) {
            sectionName = QString("CONDITION_%1").arg(i);
        }
        QVariantMap section;
        if (!c.value("name").toString().isEmpty())
            section.insert("NAME", c.value("name").toString());
        if (!c.value("input").toString().isEmpty())
            section.insert("INPUT", c.value("input").toString());
        section.insert("FLASHING_FREQUENCY", QString::number(c.value("flashingFrequency", 0.0).toDouble()));
        section.insert("FLASHING_MIN_VALUE", QString::number(c.value("flashingMinValue", 0.0).toDouble()));
        section.insert("FLASHING_NOISE_AMPLITUDE", QString::number(c.value("flashingNoiseAmplitude", 0.0).toDouble()));
        section.insert("FLASHING_SKIP_OFF_STATE", c.value("flashingSkippedOffState", false).toBool() ? "1" : "0");
        section.insert("FLASHING_SKIP_DOWNHILL_STATE", c.value("flashingSkippedDownhillState", false).toBool() ? "1" : "0");
        section.insert("FLASHING_SYNCED", c.value("flashingSynced", false).toBool() ? "1" : "0");
        if (!c.value("flashingSmoothness").toString().isEmpty())
            section.insert("FLASHING_SMOOTHNESS", c.value("flashingSmoothness").toString());
        if (!c.value("flashingLut").toString().isEmpty())
            section.insert("FLASHING_LUT", c.value("flashingLut").toString());
        section.insert("LAG", QString::number(c.value("lag", 0.0).toDouble()));
        section.insert("LAG_DELAY_OFF", QString::number(c.value("lagDelayOff", 1.0).toDouble()));
        section.insert("LAG_DELAY_ON", QString::number(c.value("lagDelayOn", 5.0).toDouble()));
        section.insert("SIMULATE_HEATING", QString::number(c.value("simulateHeating", 0.0).toDouble()));
        result.insert(sectionName, section);
    }
    return result;
}

// ── Editing API ───────────────────────────────────────────────────────────

QVariantMap CspConfigParser::addEmissive(QVariantMap sections, const QVariantMap& emissive) {
    int idx = 0;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (it.key().startsWith("EMISSIVE") || it.key().startsWith("EMISSIVE_LIGHT"))
            idx++;
    }
    QString sectionName = QString("EMISSIVE_%1").arg(idx);
    QVariantMap section;
    if (!emissive.value("name").toString().isEmpty())
        section.insert("NAME", emissive.value("name").toString());
    if (!emissive.value("meshName").toString().isEmpty())
        section.insert("MESHES", emissive.value("meshName").toString());
    if (!emissive.value("materialName").toString().isEmpty())
        section.insert("MATERIALS", emissive.value("materialName").toString());
    if (!emissive.value("color").toString().isEmpty())
        section.insert("COLOR", emissive.value("color").toString());
    if (!emissive.value("colorOff").toString().isEmpty())
        section.insert("OFF_COLOR", emissive.value("colorOff").toString());
    if (!emissive.value("location").toString().isEmpty())
        section.insert("LOCATION", emissive.value("location").toString());
    section.insert("LAG", QString::number(emissive.value("lag", 0.0).toDouble()));
    section.insert("ACTIVE", emissive.value("active", true).toBool() ? "1" : "0");
    sections.insert(sectionName, section);
    return sections;
}

QVariantMap CspConfigParser::removeEmissive(QVariantMap sections, const QString& sectionName) {
    sections.remove(sectionName);
    return sections;
}

QVariantMap CspConfigParser::addTrackLight(QVariantMap sections, const QVariantMap& light) {
    int idx = 0;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (it.key().startsWith("LIGHT_SERIES") || it.key().startsWith("LIGHT_"))
            idx++;
    }
    QString sectionName = QString("LIGHT_SERIES_%1").arg(idx);
    QVariantMap section;
    section.insert("ACTIVE", light.value("active", true).toBool() ? "1" : "0");
    if (!light.value("meshName").toString().isEmpty())
        section.insert("MESHES", light.value("meshName").toString());
    if (!light.value("materialName").toString().isEmpty())
        section.insert("MATERIALS", light.value("materialName").toString());
    if (!light.value("direction").toString().isEmpty())
        section.insert("DIRECTION", light.value("direction").toString());
    if (!light.value("color").toString().isEmpty())
        section.insert("COLOR", light.value("color").toString());
    if (!light.value("colorOff").toString().isEmpty())
        section.insert("COLOR_OFF", light.value("colorOff").toString());
    section.insert("SPOT", QString::number(light.value("spot", 150.0).toDouble()));
    section.insert("SPOT_SHARPNESS", QString::number(light.value("spotSharpness", 0.7).toDouble()));
    section.insert("RANGE", QString::number(light.value("range", 20.0).toDouble()));
    sections.insert(sectionName, section);
    return sections;
}

QVariantMap CspConfigParser::removeTrackLight(QVariantMap sections, const QString& sectionName) {
    sections.remove(sectionName);
    return sections;
}

QVariantMap CspConfigParser::addMaterialAdjustment(QVariantMap sections, const QVariantMap& adjustment) {
    int idx = 0;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (it.key().startsWith("MATERIAL_ADJUSTMENT"))
            idx++;
    }
    QString sectionName = QString("MATERIAL_ADJUSTMENT_%1").arg(idx);
    QVariantMap section;
    section.insert("ACTIVE", adjustment.value("active", true).toBool() ? "1" : "0");
    if (!adjustment.value("meshes").toString().isEmpty())
        section.insert("MESHES", adjustment.value("meshes").toString());
    if (!adjustment.value("materials").toString().isEmpty())
        section.insert("MATERIALS", adjustment.value("materials").toString());
    if (!adjustment.value("key0").toString().isEmpty())
        section.insert("KEY_0", adjustment.value("key0").toString());
    if (!adjustment.value("value0").toString().isEmpty())
        section.insert("VALUE_0", adjustment.value("value0").toString());
    section.insert("RANGE", QString::number(adjustment.value("range", 20.0).toDouble()));
    sections.insert(sectionName, section);
    return sections;
}

QVariantMap CspConfigParser::removeMaterialAdjustment(QVariantMap sections, const QString& sectionName) {
    sections.remove(sectionName);
    return sections;
}

QVariantMap CspConfigParser::addCondition(QVariantMap sections, const QVariantMap& condition) {
    int idx = 0;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (it.key().startsWith("CONDITION"))
            idx++;
    }
    QString sectionName = QString("CONDITION_%1").arg(idx);
    QVariantMap section;
    if (!condition.value("name").toString().isEmpty())
        section.insert("NAME", condition.value("name").toString());
    if (!condition.value("input").toString().isEmpty())
        section.insert("INPUT", condition.value("input").toString());
    section.insert("FLASHING_FREQUENCY", QString::number(condition.value("flashingFrequency", 0.0).toDouble()));
    section.insert("LAG", QString::number(condition.value("lag", 0.0).toDouble()));
    sections.insert(sectionName, section);
    return sections;
}

QVariantMap CspConfigParser::removeCondition(QVariantMap sections, const QString& sectionName) {
    sections.remove(sectionName);
    return sections;
}

QVariantMap CspConfigParser::getCarSchema() {
    QVariantMap schema;
    schema.insert("name", "CSP Car Config");
    schema.insert("version", "1.0");

    QVariantMap emissives;
    emissives.insert("type", "array");
    QVariantMap emissiveProps;
    emissiveProps.insert("name", "QString");
    emissiveProps.insert("meshName", "QString");
    emissiveProps.insert("color", "QString");
    emissiveProps.insert("colorOff", "QString");
    emissiveProps.insert("location", "QString");
    emissiveProps.insert("lag", "double");
    emissiveProps.insert("simulateHeating", "double");
    emissiveProps.insert("bindToHeadlights", "bool");
    emissiveProps.insert("active", "bool");
    emissiveProps.insert("condition", "QString");
    emissives.insert("properties", emissiveProps);
    schema.insert("emissives", emissives);

    QVariantMap brakeDiscs;
    brakeDiscs.insert("type", "array");
    QVariantMap brakeDiscProps;
    brakeDiscProps.insert("ambientMult", "double");
    brakeDiscProps.insert("reflectionMult", "double");
    brakeDiscProps.insert("discInternalRadius", "double");
    brakeDiscProps.insert("rimInternalRadius", "double");
    brakeDiscProps.insert("position", "QString");
    brakeDiscs.insert("properties", brakeDiscProps);
    schema.insert("brakeDiscs", brakeDiscs);

    return schema;
}

QVariantMap CspConfigParser::getTrackSchema() {
    QVariantMap schema;
    schema.insert("name", "CSP Track Config");
    schema.insert("version", "1.0");

    QVariantMap trackLights;
    trackLights.insert("type", "array");
    QVariantMap lightProps;
    lightProps.insert("name", "QString");
    lightProps.insert("meshName", "QString");
    lightProps.insert("materialName", "QString");
    lightProps.insert("position", "QString");
    lightProps.insert("direction", "QString");
    lightProps.insert("color", "QString");
    lightProps.insert("colorOff", "QString");
    lightProps.insert("spot", "double");
    lightProps.insert("spotSharpness", "double");
    lightProps.insert("range", "double");
    lightProps.insert("fadeAt", "double");
    lightProps.insert("fadeSmooth", "double");
    lightProps.insert("condition", "QString");
    lightProps.insert("active", "bool");
    trackLights.insert("properties", lightProps);
    schema.insert("trackLights", trackLights);

    QVariantMap materialAdjustments;
    materialAdjustments.insert("type", "array");
    QVariantMap adjustmentProps;
    adjustmentProps.insert("name", "QString");
    adjustmentProps.insert("meshes", "QString");
    adjustmentProps.insert("materials", "QString");
    adjustmentProps.insert("key0", "QString");
    adjustmentProps.insert("value0", "QString");
    adjustmentProps.insert("value0Off", "QString");
    adjustmentProps.insert("key1", "QString");
    adjustmentProps.insert("value1", "QString");
    adjustmentProps.insert("value1Off", "QString");
    adjustmentProps.insert("range", "double");
    adjustmentProps.insert("spot", "double");
    adjustmentProps.insert("spotSharpness", "double");
    adjustmentProps.insert("condition", "QString");
    adjustmentProps.insert("active", "bool");
    materialAdjustments.insert("properties", adjustmentProps);
    schema.insert("materialAdjustments", materialAdjustments);

    QVariantMap conditions;
    conditions.insert("type", "array");
    QVariantMap conditionProps;
    conditionProps.insert("name", "QString");
    conditionProps.insert("input", "QString");
    conditionProps.insert("flashingFrequency", "double");
    conditionProps.insert("flashingMinValue", "double");
    conditionProps.insert("flashingSkippedOffState", "bool");
    conditionProps.insert("flashingSynced", "bool");
    conditionProps.insert("flashingLut", "QString");
    conditionProps.insert("lag", "double");
    conditionProps.insert("simulateHeating", "double");
    conditions.insert("properties", conditionProps);
    schema.insert("conditions", conditions);

    return schema;
}

QString CspConfigParser::colorToString(const QVariantMap& colorMap)
{
    int r = colorMap.value("r", 255).toInt();
    int g = colorMap.value("g", 255).toInt();
    int b = colorMap.value("b", 255).toInt();
    int a = colorMap.value("a", 255).toInt();
    return QString("rgba(%1, %2, %3, %4)").arg(r).arg(g).arg(b).arg(a);
}

QVariantMap CspConfigParser::stringToColor(const QString& colorStr)
{
    QVariantMap result;
    result["r"] = 255;
    result["g"] = 255;
    result["b"] = 255;
    result["a"] = 255;

    QRegularExpression re(R"(rgba?\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*(\d+))?\s*\))");
    QRegularExpressionMatch m = re.match(colorStr.trimmed());
    if (m.hasMatch()) {
        result["r"] = m.captured(1).toInt();
        result["g"] = m.captured(2).toInt();
        result["b"] = m.captured(3).toInt();
        result["a"] = m.captured(4).isEmpty() ? 255 : m.captured(4).toInt();
    } else if (colorStr.startsWith("#")) {
        QColor c(colorStr);
        if (c.isValid()) {
            result["r"] = c.red();
            result["g"] = c.green();
            result["b"] = c.blue();
            result["a"] = c.alpha();
        }
    }
    return result;
}

QString CspConfigParser::positionToString(const QVariantMap& posMap)
{
    double x = posMap.value("x", 0.0).toDouble();
    double y = posMap.value("y", 0.0).toDouble();
    double z = posMap.value("z", 0.0).toDouble();
    return QString("%1,%2,%3").arg(x, 0, 'f', 4).arg(y, 0, 'f', 4).arg(z, 0, 'f', 4);
}

QVariantMap CspConfigParser::stringToPosition(const QString& posStr)
{
    QVariantMap result;
    result["x"] = 0.0;
    result["y"] = 0.0;
    result["z"] = 0.0;

    QStringList parts = posStr.split(',', Qt::SkipEmptyParts);
    if (parts.size() >= 3) {
        result["x"] = parts[0].trimmed().toDouble();
        result["y"] = parts[1].trimmed().toDouble();
        result["z"] = parts[2].trimmed().toDouble();
    }
    return result;
}

}