#include "CspConfigHandler.h"
#include "../../../../../core/ServerConfigEditor/CspShaderCompiler.h"
#include <QFile>
#include <QTextStream>
#include <QFileInfo>
#include <QDir>
#include <QDebug>
#include <QRegularExpression>

namespace ks {

CspConfigHandler* CspConfigHandler::s_instance = nullptr;

CspConfigHandler::CspConfigHandler(QObject* parent) : QObject(parent) {}

CspConfigHandler* CspConfigHandler::instance() {
    if (!s_instance) {
        s_instance = new CspConfigHandler();
    }
    return s_instance;
}

// ── INI Parsing ──────────────────────────────────────────────────────────────

QVariantMap CspConfigHandler::parseIniFile(const QString& path) {
    QVariantMap root;
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return root;

    QTextStream in(&file);
    in.setEncoding(QStringConverter::Utf8);
    QString currentSection;
    static QRegularExpression sectionRe(R"(\[([^\]]+)\])");
    static QRegularExpression commentRe(R"(^(;|#).*)");

    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();

        if (line.isEmpty() || commentRe.match(line).hasMatch())
            continue;

        QRegularExpressionMatch sectionMatch = sectionRe.match(line);
        if (sectionMatch.hasMatch()) {
            currentSection = sectionMatch.captured(1).trimmed();
            if (!root.contains(currentSection))
                root[currentSection] = QVariantMap();
            continue;
        }

        int eq = line.indexOf('=');
        if (eq > 0 && !currentSection.isEmpty()) {
            QString key = line.left(eq).trimmed();
            QString val = line.mid(eq + 1).trimmed();
            if (val.startsWith('"') && val.endsWith('"'))
                val = val.mid(1, val.size() - 2);
            if (!key.isEmpty()) {
                QVariantMap section = root[currentSection].toMap();
                section[key] = val;
                root[currentSection] = section;
            }
        }
    }

    file.close();
    return root;
}

bool CspConfigHandler::writeIniFile(const QString& path, const QVariantMap& sections) {
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;

    QTextStream out(&file);
    out.setEncoding(QStringConverter::Utf8);
    out << "; Generated by ksEditor CSP Config Editor\n\n";

    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        out << "[" << it.key() << "]\n";
        const QVariant sectionVal = it.value();
        if (sectionVal.typeId() == QVariant::Map) {
            QVariantMap keys = sectionVal.toMap();
            for (auto keyIt = keys.constBegin(); keyIt != keys.constEnd(); ++keyIt) {
                out << keyIt.key() << "=" << keyIt.value().toString() << "\n";
            }
        }
        out << "\n";
    }

    file.close();
    return true;
}

// ── Load / Save ──────────────────────────────────────────────────────────────

QVariantMap CspConfigHandler::loadConfig(const QString& path) {
    return parseIniFile(path);
}

bool CspConfigHandler::saveConfig(const QString& path, const QVariantMap& sections) {
    QDir().mkpath(QFileInfo(path).absolutePath());
    return writeIniFile(path, sections);
}

QVariantMap CspConfigHandler::loadWithIncludes(const QString& path) {
    QVariantMap config = parseIniFile(path);
    QString basePath = QFileInfo(path).absolutePath();

    QStringList includeKeys;
    for (auto it = config.constBegin(); it != config.constEnd(); ++it) {
        if (it.key().startsWith("INCLUDE")) {
            includeKeys.append(it.key());
        }
    }

    QVariantMap merged;
    for (const QString& key : includeKeys) {
        QVariantMap section = config.value(key).toMap();
        QString includePath = section.value("INCLUDE").toString();
        if (!includePath.isEmpty()) {
            QString resolvedPath = resolveIncludePath(basePath, includePath);
            if (QFileInfo::exists(resolvedPath)) {
                QVariantMap included = parseIniFile(resolvedPath);
                merged = mergeConfigs(merged, included);
            }
        }
    }

    merged = mergeConfigs(merged, config);
    return merged;
}

QVariantMap CspConfigHandler::mergeConfigs(const QVariantMap& base, const QVariantMap& overlay) {
    QVariantMap result = base;
    for (auto it = overlay.constBegin(); it != overlay.constEnd(); ++it) {
        if (it.key().startsWith("INCLUDE")) continue;
        if (result.contains(it.key())) {
            QVariantMap baseSection = result[it.key()].toMap();
            QVariantMap overlaySection = it.value().toMap();
            for (auto kIt = overlaySection.constBegin(); kIt != overlaySection.constEnd(); ++kIt) {
                baseSection[kIt.key()] = kIt.value();
            }
            result[it.key()] = baseSection;
        } else {
            result[it.key()] = it.value();
        }
    }
    return result;
}

QString CspConfigHandler::resolveIncludePath(const QString& basePath, const QString& includePath) {
    if (QFileInfo(includePath).isAbsolute())
        return includePath;
    return QDir(basePath).absoluteFilePath(includePath);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

bool CspConfigHandler::isSectionType(const QString& sectionName, const QString& type) {
    QString name = sectionName.toUpper();
    QString upperType = type.toUpper();

    if (upperType == "LIGHT_SERIES")
        return name.startsWith("LIGHT_SERIES_") || name.startsWith("LIGHT_SERIES...");
    if (upperType == "MATERIAL_ADJUSTMENT")
        return name.startsWith("MATERIAL_ADJUSTMENT_") || name.startsWith("MATERIAL_ADJUSTMENT...");
    if (upperType == "CONDITION")
        return name.startsWith("CONDITION_") || name.startsWith("CONDITION...");
    if (upperType == "LIGHT")
        return (name.startsWith("LIGHT_") && !name.startsWith("LIGHT_SERIES") &&
                name != "LIGHTING" && name != "LIGHT_POLLUTION");
    if (upperType == "SHADER_REPLACEMENT")
        return name.startsWith("SHADER_REPLACEMENT_") || name.startsWith("SHADER_REPLACEMENT...");
    if (upperType == "MODEL_REPLACEMENT")
        return name.startsWith("MODEL_REPLACEMENT_") || name.startsWith("MODEL_REPLACEMENT...");
    if (upperType == "INCLUDE")
        return name.startsWith("INCLUDE");
    if (upperType == "EMISSIVE")
        return name.startsWith("EMISSIVE_") || name.startsWith("EMISSIVE_LIGHT");
    if (upperType == "BRAKEDISC")
        return name.startsWith("BRAKEDISC_FX");
    if (upperType == "CUSTOMEMISSIVE")
        return name == "CUSTEMISSIVE" || name.startsWith("CUSTOMEMISSIVE");
    if (upperType == "CUSTOMEMISSIVEMULTI")
        return name == "CUSTOMEMISSIVEMULTI";
    if (upperType == "MATERIAL_DISTANTEMISSIVE")
        return name == "MATERIAL_DISTANTEMISSIVE";
    if (upperType == "MATERIAL_ROOMWINDOWS")
        return name == "MATERIAL_ROOMWINDOWS";
    if (upperType == "ABOUT")
        return name == "ABOUT";
    if (upperType == "LIGHTING")
        return name == "LIGHTING";
    if (upperType == "REFLECTIONS_FX")
        return name == "REFLECTIONS_FX";
    if (upperType == "PARTICLES_FX")
        return name == "PARTICLES_FX";
    if (upperType == "RAIN_FX")
        return name == "RAIN_FX";
    if (upperType == "GRASS_FX")
        return name == "GRASS_FX";
    if (upperType == "WIND")
        return name == "WIND";
    if (upperType == "BOUNCED_LIGHT")
        return name == "BOUNCED_LIGHT";
    if (upperType == "BOUNCED_INTERIOR_LIGHT")
        return name == "BOUNCED_INTERIOR_LIGHT";
    if (upperType == "SMART_MIRROR")
        return name == "SMART_MIRROR";
    if (upperType == "INSTRUMENTS")
        return name == "INSTRUMENTS";
    if (upperType == "ODOMETER")
        return name.startsWith("ODOMETER_");
    if (upperType == "DEFORMING")
        return name.startsWith("DEFORMING_");
    if (upperType == "TYRES_FX")
        return name == "TYRES_FX";
    if (upperType == "REFRACTING_HEADLIGHT")
        return name.startsWith("REFRACTING_HEADLIGHT");
    if (upperType == "ANIMATED_WIPER")
        return name.startsWith("ANIMATED_WIPER_");
    if (upperType == "SHAKING_EXHAUST")
        return name.startsWith("SHAKING_EXHAUST_");
    if (upperType == "SIDE_NET")
        return name.startsWith("SIDE_NET_");
    if (upperType == "MESH_ADJUSTMENT")
        return name.startsWith("MESH_ADJUSTMENT_");
    if (upperType == "TRACK_OCCLUDER")
        return name.startsWith("TRACK_OCCLUDER_");
    if (upperType == "BASIC")
        return name == "BASIC";

    return name.startsWith(upperType + "_") || name == upperType;
}

QString CspConfigHandler::generateSectionName(const QString& type, const QVariantMap& existingSections) {
    int idx = findNextIndex(existingSections, type);
    return QString("%1_%2").arg(type).arg(idx);
}

int CspConfigHandler::findNextIndex(const QVariantMap& sections, const QString& type) {
    int maxIdx = -1;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (isSectionType(it.key(), type)) {
            QRegularExpression re(QString(R"((\d+)\.\.\.|\b(\d+)$)"));
            QRegularExpressionMatch m = re.match(it.key());
            if (m.hasMatch()) {
                if (!m.captured(1).isEmpty()) {
                    return -1;
                }
                int idx = m.captured(2).toInt();
                if (idx > maxIdx) maxIdx = idx;
            }
        }
    }
    return maxIdx + 1;
}

QStringList CspConfigHandler::extractList(const QString& str) {
    QStringList result;
    if (str.isEmpty()) return result;
    for (const QString& s : str.split(',', Qt::SkipEmptyParts)) {
        result.append(s.trimmed());
    }
    return result;
}

QString CspConfigHandler::joinList(const QStringList& list) {
    return list.join(", ");
}

QStringList CspConfigHandler::getAvailableSectionTypes() {
    return {
        "INCLUDE", "ABOUT", "BASIC", "LIGHTING", "REFLECTIONS_FX", "PARTICLES_FX",
        "RAIN_FX", "GRASS_FX", "WIND", "BOUNCED_LIGHT", "BOUNCED_INTERIOR_LIGHT",
        "SMART_MIRROR", "INSTRUMENTS", "ODOMETER", "DEFORMING", "TYRES_FX",
        "REFRACTING_HEADLIGHT", "ANIMATED_WIPER", "SHAKING_EXHAUST", "SIDE_NET",
        "MESH_ADJUSTMENT", "TRACK_OCCLUDER",
        "LIGHT_SERIES", "LIGHT", "MATERIAL_ADJUSTMENT", "CONDITION",
        "SHADER_REPLACEMENT", "MODEL_REPLACEMENT",
        "EMISSIVE", "BRAKEDISC",
        "CUSTOMEMISSIVE", "CUSTOMEMISSIVEMULTI",
        "MATERIAL_DISTANTEMISSIVE", "MATERIAL_ROOMWINDOWS"
    };
}

QStringList CspConfigHandler::findSectionsByType(const QVariantMap& sections, const QString& type) {
    QStringList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (isSectionType(it.key(), type))
            result.append(it.key());
    }
    return result;
}

QVariantList CspConfigHandler::getSectionProperties(const QVariantMap& sections, const QString& sectionName) {
    QVariantList result;
    if (!sections.contains(sectionName)) return result;
    QVariantMap section = sections[sectionName].toMap();
    for (auto it = section.constBegin(); it != section.constEnd(); ++it) {
        QVariantMap prop;
        prop["key"] = it.key();
        prop["value"] = it.value();
        result.append(prop);
    }
    return result;
}

// ── Parse: Light Series ──────────────────────────────────────────────────────

QVariantList CspConfigHandler::parseLightSeries(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "LIGHT_SERIES")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap light;
        light["sectionName"] = it.key();
        light["active"] = section.value("ACTIVE", "1").toString() == "1";
        light["description"] = section.value("DESCRIPTION").toString();
        light["meshName"] = section.value("MESHES").toString();
        light["materialName"] = section.value("MATERIALS").toString();
        light["offset"] = section.value("OFFSET").toString();
        light["direction"] = section.value("DIRECTION").toString();
        light["position"] = section.value("POSITION").toString();
        light["spot"] = section.value("SPOT", "150").toDouble();
        light["spotSharpness"] = section.value("SPOT_SHARPNESS", "0.7").toDouble();
        light["range"] = section.value("RANGE", "20").toDouble();
        light["rangeGradientOffset"] = section.value("RANGE_GRADIENT_OFFSET", "0.5").toDouble();
        light["fadeAt"] = section.value("FADE_AT", "700").toDouble();
        light["fadeSmooth"] = section.value("FADE_SMOOTH", "100").toDouble();
        light["clusterThreshold"] = section.value("CLUSTER_THRESHOLD", "10").toInt();
        light["diffuseConcentration"] = section.value("DIFFUSE_CONCENTRATION", "0.5").toDouble();
        light["specularMult"] = section.value("SPECULAR_MULT", "1.0").toDouble();
        light["color"] = section.value("COLOR").toString();
        light["colorOff"] = section.value("COLOR_OFF").toString();
        light["condition"] = section.value("CONDITION").toString();
        light["visibilityLevel"] = section.value("VISIBILITY_LEVEL", "0").toInt();
        light["singleFrequency"] = section.value("SINGLE_FREQUENCY").toString();
        result.append(light);
    }
    return result;
}

// ── Parse: Material Adjustments ──────────────────────────────────────────────

QVariantList CspConfigHandler::parseMaterialAdjustments(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "MATERIAL_ADJUSTMENT")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap adj;
        adj["sectionName"] = it.key();
        adj["active"] = section.value("ACTIVE", "1").toString() == "1";
        adj["description"] = section.value("DESCRIPTION").toString();
        adj["meshName"] = section.value("MESHES").toString();
        adj["materialName"] = section.value("MATERIALS").toString();
        adj["condition"] = section.value("CONDITION").toString();
        adj["visibilityLevel"] = section.value("VISIBILITY_LEVEL", "0").toInt();
        adj["blendMode"] = section.value("BLEND_MODE").toString();
        adj["range"] = section.value("RANGE", "20").toDouble();
        adj["rangeGradientOffset"] = section.value("RANGE_GRADIENT_OFFSET", "0.2").toDouble();
        adj["spot"] = section.value("SPOT", "75").toDouble();
        adj["spotSharpness"] = section.value("SPOT_SHARPNESS", "0.5").toDouble();

        QVariantList keyValues;
        for (int k = 0; k < 10; ++k) {
            QString keyKey = QString("KEY_%1").arg(k);
            QString valKey = QString("VALUE_%1").arg(k);
            QString offKey = QString("VALUE_%1_OFF").arg(k);
            QString offValKey = QString("OFF_VALUE_%1").arg(k);
            if (section.contains(keyKey) || section.contains(valKey)) {
                QVariantMap kv;
                kv["key"] = section.value(keyKey).toString();
                kv["value"] = section.value(valKey).toString();
                kv["off"] = section.contains(offKey) ? section.value(offKey).toString() : section.value(offValKey).toString();
                keyValues.append(kv);
            }
        }
        adj["keyValues"] = keyValues;
        result.append(adj);
    }
    return result;
}

// ── Parse: Conditions ────────────────────────────────────────────────────────

QVariantList CspConfigHandler::parseConditions(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "CONDITION")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap cond;
        cond["sectionName"] = it.key();
        cond["name"] = section.value("NAME").toString();
        cond["input"] = section.value("INPUT").toString();
        cond["flashingFrequency"] = section.value("FLASHING_FREQUENCY", "0").toDouble();
        cond["flashingMinValue"] = section.value("FLASHING_MIN_VALUE", "0").toDouble();
        cond["flashingNoiseAmplitude"] = section.value("FLASHING_NOISE_AMPLITUDE", "0").toDouble();
        cond["flashingNoiseBound"] = section.value("FLASHING_NOISE_BOUND", "0").toDouble();
        cond["flashingNoiseSpeed"] = section.value("FLASHING_NOISE_SPEED", "500").toDouble();
        cond["flashingSkippedOffState"] = section.value("FLASHING_SKIP_OFF_STATE", "0").toString() == "1";
        cond["flashingSkippedDownhillState"] = section.value("FLASHING_SKIP_DOWNHILL_STATE", "0").toString() == "1";
        cond["flashingSynced"] = section.value("FLASHING_SYNCED", "0").toString() == "1";
        cond["flashingSmoothness"] = section.value("FLASHING_SMOOTHNESS").toString();
        cond["flashingLut"] = section.value("FLASHING_LUT").toString();
        cond["inputChangeDelay"] = section.value("INPUT_CHANGE_DELAY", "0.5").toDouble();
        cond["inputStayFor"] = section.value("INPUT_STAY_FOR", "1.0").toDouble();
        cond["lag"] = section.value("LAG", "0").toDouble();
        cond["lagDelayOff"] = section.value("LAG_DELAY_OFF", "1").toDouble();
        cond["lagDelayOn"] = section.value("LAG_DELAY_ON", "5").toDouble();
        cond["lagDelayFunc"] = section.value("LAG_DELAY_FUNC").toString();
        cond["simulateHeating"] = section.value("SIMULATE_HEATING", "0").toDouble();
        cond["delay"] = section.value("DELAY").toString();
        cond["lut"] = section.value("LUT").toString();
        result.append(cond);
    }
    return result;
}

// ── Parse: Lights ────────────────────────────────────────────────────────────

QVariantList CspConfigHandler::parseLights(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "LIGHT")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap light;
        light["sectionName"] = it.key();
        light["active"] = section.value("ACTIVE", "1").toString() == "1";
        light["description"] = section.value("DESCRIPTION").toString();
        light["meshName"] = section.value("MESHES").toString();
        light["materialName"] = section.value("MATERIALS").toString();
        light["offset"] = section.value("OFFSET").toString();
        light["direction"] = section.value("DIRECTION").toString();
        light["lineFrom"] = section.value("LINE_FROM").toString();
        light["lineTo"] = section.value("LINE_TO").toString();
        light["position"] = section.value("POSITION").toString();
        light["spot"] = section.value("SPOT", "150").toDouble();
        light["spotSharpness"] = section.value("SPOT_SHARPNESS", "0.7").toDouble();
        light["range"] = section.value("RANGE", "20").toDouble();
        light["fadeAt"] = section.value("FADE_AT", "700").toDouble();
        light["fadeSmooth"] = section.value("FADE_SMOOTH", "100").toDouble();
        light["diffuseConcentration"] = section.value("DIFFUSE_CONCENTRATION", "0.5").toDouble();
        light["color"] = section.value("COLOR").toString();
        light["condition"] = section.value("CONDITION").toString();
        light["visibilityLevel"] = section.value("VISIBILITY_LEVEL", "0").toInt();
        result.append(light);
    }
    return result;
}

// ── Parse: Shader Replacements ───────────────────────────────────────────────

QVariantList CspConfigHandler::parseShaderReplacements(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "SHADER_REPLACEMENT")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap repl;
        repl["sectionName"] = it.key();
        repl["meshName"] = section.value("MESHES").toString();
        repl["materialName"] = section.value("MATERIALS").toString();
        repl["shader"] = section.value("SHADER").toString();
        repl["blendMode"] = section.value("BLEND_MODE").toString();
        repl["isTransparent"] = section.value("IS_TRANSPARENT").toString();
        repl["doubleFaceShadowBiased"] = section.value("DOUBLE_FACE_SHADOW_BIASED").toString();
        repl["lodIn"] = section.value("LOD_IN").toString();
        repl["lodOut"] = section.value("LOD_OUT").toString();

        QVariantList props;
        for (auto kIt = section.constBegin(); kIt != section.constEnd(); ++kIt) {
            if (kIt.key().startsWith("PROP_")) {
                QVariantMap prop;
                prop["key"] = kIt.key();
                prop["value"] = kIt.value();
                props.append(prop);
            }
        }
        repl["properties"] = props;
        result.append(repl);
    }
    return result;
}

// ── Parse: Model Replacements ────────────────────────────────────────────────

QVariantList CspConfigHandler::parseModelReplacements(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "MODEL_REPLACEMENT")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap repl;
        repl["sectionName"] = it.key();
        repl["file"] = section.value("FILE").toString();
        repl["insert"] = section.value("INSERT").toString();
        repl["insertAfter"] = section.value("INSERT_AFTER").toString();
        repl["description"] = section.value("DESCRIPTION").toString();
        result.append(repl);
    }
    return result;
}

// ── Parse: Includes ──────────────────────────────────────────────────────────

QVariantList CspConfigHandler::parseIncludes(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "INCLUDE")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap inc;
        inc["sectionName"] = it.key();
        inc["include"] = section.value("INCLUDE").toString();
        result.append(inc);
    }
    return result;
}

// ── Parse: Emissives ─────────────────────────────────────────────────────────

QVariantList CspConfigHandler::parseEmissives(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "EMISSIVE")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap em;
        em["sectionName"] = it.key();
        em["name"] = section.value("NAME").toString();
        em["meshName"] = section.value("MESHES").toString();
        em["materialName"] = section.value("MATERIALS").toString();
        em["color"] = section.value("COLOR").toString();
        em["colorOff"] = section.value("OFF_COLOR").toString();
        em["location"] = section.value("LOCATION").toString();
        em["channel"] = section.value("CHANNEL").toString();
        em["lag"] = section.value("LAG", "0").toDouble();
        em["simulateHeating"] = section.value("SIMULATE_HEATING", "0").toDouble();
        em["bindToHeadlights"] = section.value("BIND_TO_HEADLIGHTS", "0").toString() == "1";
        em["active"] = section.value("ACTIVE", "1").toString() == "1";
        em["condition"] = section.value("CONDITION").toString();
        result.append(em);
    }
    return result;
}

// ── Parse: Brake Discs ───────────────────────────────────────────────────────

QVariantList CspConfigHandler::parseBrakeDiscs(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "BRAKEDISC")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap disc;
        disc["sectionName"] = it.key();
        disc["ambientMult"] = section.value("AMBIENT_MULT", "0.6").toDouble();
        disc["reflectionMult"] = section.value("REFLECTION_MULT", "1.0").toDouble();
        disc["discInternalRadius"] = section.value("DISC_INTERNAL_RADIUS", "0.126").toDouble();
        disc["discInternalRadiusSharpness"] = section.value("DISC_INTERNAL_RADIUS_SHARPNESS", "250").toDouble();
        disc["rimInternalRadius"] = section.value("RIM_INTERNAL_RADIUS", "0.06").toDouble();
        disc["simplifyNormalsK"] = section.value("SIMPLIFY_NORMALS_K", "0.9").toDouble();
        if (it.key().contains("FRONT"))
            disc["position"] = "front";
        else if (it.key().contains("REAR"))
            disc["position"] = "rear";
        else
            disc["position"] = "all";
        result.append(disc);
    }
    return result;
}

// ── Parse: Custom Emissives ──────────────────────────────────────────────────

QVariantList CspConfigHandler::parseCustomEmissives(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (!isSectionType(it.key(), "CUSTOMEMISSIVE")) continue;
        QVariantMap section = it.value().toMap();
        QVariantMap em;
        em["sectionName"] = it.key();
        em["meshes"] = section.value("Meshes").toString();
        em["materials"] = section.value("Materials").toString();
        em["active"] = section.value("ACTIVE", "1").toString() == "1";
        em["description"] = section.value("DESCRIPTION").toString();
        em["resolution"] = section.value("Resolution").toString();
        em["shader"] = section.value("SHADER").toString();
        em["colorMasksAsMultiplier"] = section.value("ColorMasksAsMultiplier").toString();
        em["areasSubtractive"] = section.value("AreasSubtractive").toString();

        QVariantList directives;
        for (auto kIt = section.constBegin(); kIt != section.constEnd(); ++kIt) {
            if (kIt.key().startsWith("@")) {
                QVariantMap dir;
                dir["directive"] = kIt.key();
                dir["value"] = kIt.value();
                directives.append(dir);
            }
        }
        em["directives"] = directives;
        result.append(em);
    }
    return result;
}

// ── Parse: Custom Emissive Multis ────────────────────────────────────────────

QVariantList CspConfigHandler::parseCustomEmissiveMultis(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (it.key() != "CustomEmissiveMulti") continue;
        QVariantMap section = it.value().toMap();
        QVariantMap em;
        em["sectionName"] = it.key();
        em["meshes"] = section.value("Meshes").toString();
        em["resolution"] = section.value("Resolution").toString();

        QVariantList directives;
        for (auto kIt = section.constBegin(); kIt != section.constEnd(); ++kIt) {
            if (kIt.key().startsWith("@")) {
                QVariantMap dir;
                dir["directive"] = kIt.key();
                dir["value"] = kIt.value();
                directives.append(dir);
            }
        }
        em["directives"] = directives;
        result.append(em);
    }
    return result;
}

// ── Parse: Material Distant Emissives ────────────────────────────────────────

QVariantList CspConfigHandler::parseMaterialDistantEmissives(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (it.key() != "Material_DistantEmissive") continue;
        QVariantMap section = it.value().toMap();
        QVariantMap em;
        em["sectionName"] = it.key();
        em["materials"] = section.value("Materials").toString();
        em["meshes"] = section.value("Meshes").toString();
        em["floodlightPower"] = section.value("FloodlightPower", "1").toDouble();
        em["distanceMult"] = section.value("DistanceMult_v2", "1").toDouble();
        em["dotBrightnessCenter"] = section.value("DotBrightnessCenter_v2", "1").toDouble();
        result.append(em);
    }
    return result;
}

// ── Parse: Material Room Windows ─────────────────────────────────────────────

QVariantList CspConfigHandler::parseMaterialRoomWindows(const QVariantMap& sections) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (it.key() != "Material_RoomWindows") continue;
        QVariantMap section = it.value().toMap();
        QVariantMap win;
        win["sectionName"] = it.key();
        win["materials"] = section.value("Materials").toString();
        win["roomHeight"] = section.value("RoomHeight", "3.5").toDouble();
        win["roomDepth"] = section.value("RoomDepth", "5.0").toDouble();
        win["roomCeilingRotation"] = section.value("RoomCeilingRotation", "0").toDouble();
        win["roomCeilingScale"] = section.value("RoomCeilingScale", "0.45").toDouble();
        result.append(win);
    }
    return result;
}

// ── Parse: About ─────────────────────────────────────────────────────────────

QVariantList CspConfigHandler::parseAbout(const QVariantMap& sections) {
    QVariantList result;
    if (sections.contains("ABOUT")) {
        QVariantMap section = sections["ABOUT"].toMap();
        QVariantMap about;
        about["sectionName"] = "ABOUT";
        about["author"] = section.value("AUTHOR").toString();
        about["version"] = section.value("VERSION").toString();
        about["dateRelease"] = section.value("DATE_RELEASE").toString();
        about["lightsCount"] = section.value("LIGHTS_COUNT").toString();
        about["notes"] = section.value("NOTES").toString();
        result.append(about);
    }
    return result;
}

// ── Parse: Single Section (generic) ──────────────────────────────────────────

QVariantList CspConfigHandler::parseSingleSection(const QVariantMap& sections, const QString& type) {
    QVariantList result;
    for (auto it = sections.constBegin(); it != sections.constEnd(); ++it) {
        if (isSectionType(it.key(), type)) {
            QVariantMap sec;
            sec["sectionName"] = it.key();
            sec["data"] = it.value();
            result.append(sec);
        }
    }
    return result;
}

// ── Serialize: Light Series ──────────────────────────────────────────────────

QVariantMap CspConfigHandler::serializeLightSeries(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap l = items.at(i).toMap();
        QString name = l.value("sectionName").toString();
        if (name.isEmpty()) name = QString("LIGHT_SERIES_%1").arg(i);
        QVariantMap section;
        section["ACTIVE"] = l.value("active", true).toBool() ? "1" : "0";
        if (!l.value("description").toString().isEmpty()) section["DESCRIPTION"] = l.value("description").toString();
        if (!l.value("meshName").toString().isEmpty()) section["MESHES"] = l.value("meshName").toString();
        if (!l.value("materialName").toString().isEmpty()) section["MATERIALS"] = l.value("materialName").toString();
        if (!l.value("offset").toString().isEmpty()) section["OFFSET"] = l.value("offset").toString();
        if (!l.value("direction").toString().isEmpty()) section["DIRECTION"] = l.value("direction").toString();
        if (!l.value("position").toString().isEmpty()) section["POSITION"] = l.value("position").toString();
        section["SPOT"] = QString::number(l.value("spot", 150.0).toDouble());
        section["SPOT_SHARPNESS"] = QString::number(l.value("spotSharpness", 0.7).toDouble());
        section["RANGE"] = QString::number(l.value("range", 20.0).toDouble());
        section["RANGE_GRADIENT_OFFSET"] = QString::number(l.value("rangeGradientOffset", 0.5).toDouble());
        section["FADE_AT"] = QString::number(l.value("fadeAt", 700.0).toDouble());
        section["FADE_SMOOTH"] = QString::number(l.value("fadeSmooth", 100.0).toDouble());
        section["CLUSTER_THRESHOLD"] = QString::number(l.value("clusterThreshold", 10).toInt());
        section["DIFFUSE_CONCENTRATION"] = QString::number(l.value("diffuseConcentration", 0.5).toDouble());
        section["SPECULAR_MULT"] = QString::number(l.value("specularMult", 1.0).toDouble());
        if (!l.value("color").toString().isEmpty()) section["COLOR"] = l.value("color").toString();
        if (!l.value("colorOff").toString().isEmpty()) section["COLOR_OFF"] = l.value("colorOff").toString();
        if (!l.value("condition").toString().isEmpty()) section["CONDITION"] = l.value("condition").toString();
        result[name] = section;
    }
    return result;
}

// ── Serialize: Material Adjustments ──────────────────────────────────────────

QVariantMap CspConfigHandler::serializeMaterialAdjustments(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap a = items.at(i).toMap();
        QString name = a.value("sectionName").toString();
        if (name.isEmpty()) name = QString("MATERIAL_ADJUSTMENT_%1").arg(i);
        QVariantMap section;
        section["ACTIVE"] = a.value("active", true).toBool() ? "1" : "0";
        if (!a.value("description").toString().isEmpty()) section["DESCRIPTION"] = a.value("description").toString();
        if (!a.value("meshName").toString().isEmpty()) section["MESHES"] = a.value("meshName").toString();
        if (!a.value("materialName").toString().isEmpty()) section["MATERIALS"] = a.value("materialName").toString();
        if (!a.value("condition").toString().isEmpty()) section["CONDITION"] = a.value("condition").toString();
        if (!a.value("blendMode").toString().isEmpty()) section["BLEND_MODE"] = a.value("blendMode").toString();
        section["RANGE"] = QString::number(a.value("range", 20.0).toDouble());
        section["RANGE_GRADIENT_OFFSET"] = QString::number(a.value("rangeGradientOffset", 0.2).toDouble());
        section["SPOT"] = QString::number(a.value("spot", 75.0).toDouble());
        section["SPOT_SHARPNESS"] = QString::number(a.value("spotSharpness", 0.5).toDouble());
        QVariantList keyValues = a.value("keyValues").toList();
        for (int k = 0; k < keyValues.size(); ++k) {
            QVariantMap kv = keyValues.at(k).toMap();
            section[QString("KEY_%1").arg(k)] = kv.value("key").toString();
            section[QString("VALUE_%1").arg(k)] = kv.value("value").toString();
            if (!kv.value("off").toString().isEmpty())
                section[QString("VALUE_%1_OFF").arg(k)] = kv.value("off").toString();
        }
        result[name] = section;
    }
    return result;
}

// ── Serialize: Conditions ────────────────────────────────────────────────────

QVariantMap CspConfigHandler::serializeConditions(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap c = items.at(i).toMap();
        QString name = c.value("sectionName").toString();
        if (name.isEmpty()) name = QString("CONDITION_%1").arg(i);
        QVariantMap section;
        if (!c.value("name").toString().isEmpty()) section["NAME"] = c.value("name").toString();
        if (!c.value("input").toString().isEmpty()) section["INPUT"] = c.value("input").toString();
        section["FLASHING_FREQUENCY"] = QString::number(c.value("flashingFrequency", 0.0).toDouble());
        section["FLASHING_MIN_VALUE"] = QString::number(c.value("flashingMinValue", 0.0).toDouble());
        section["FLASHING_NOISE_AMPLITUDE"] = QString::number(c.value("flashingNoiseAmplitude", 0.0).toDouble());
        section["FLASHING_SKIP_OFF_STATE"] = c.value("flashingSkippedOffState", false).toBool() ? "1" : "0";
        section["FLASHING_SKIP_DOWNHILL_STATE"] = c.value("flashingSkippedDownhillState", false).toBool() ? "1" : "0";
        section["FLASHING_SYNCED"] = c.value("flashingSynced", false).toBool() ? "1" : "0";
        if (!c.value("flashingSmoothness").toString().isEmpty()) section["FLASHING_SMOOTHNESS"] = c.value("flashingSmoothness").toString();
        if (!c.value("flashingLut").toString().isEmpty()) section["FLASHING_LUT"] = c.value("flashingLut").toString();
        section["LAG"] = QString::number(c.value("lag", 0.0).toDouble());
        section["LAG_DELAY_OFF"] = QString::number(c.value("lagDelayOff", 1.0).toDouble());
        section["LAG_DELAY_ON"] = QString::number(c.value("lagDelayOn", 5.0).toDouble());
        section["SIMULATE_HEATING"] = QString::number(c.value("simulateHeating", 0.0).toDouble());
        if (!c.value("delay").toString().isEmpty()) section["DELAY"] = c.value("delay").toString();
        if (!c.value("lut").toString().isEmpty()) section["LUT"] = c.value("lut").toString();
        result[name] = section;
    }
    return result;
}

// ── Serialize: Lights ────────────────────────────────────────────────────────

QVariantMap CspConfigHandler::serializeLights(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap l = items.at(i).toMap();
        QString name = l.value("sectionName").toString();
        if (name.isEmpty()) name = QString("LIGHT_%1").arg(i);
        QVariantMap section;
        section["ACTIVE"] = l.value("active", true).toBool() ? "1" : "0";
        if (!l.value("description").toString().isEmpty()) section["DESCRIPTION"] = l.value("description").toString();
        if (!l.value("meshName").toString().isEmpty()) section["MESHES"] = l.value("meshName").toString();
        if (!l.value("materialName").toString().isEmpty()) section["MATERIALS"] = l.value("materialName").toString();
        if (!l.value("lineFrom").toString().isEmpty()) section["LINE_FROM"] = l.value("lineFrom").toString();
        if (!l.value("lineTo").toString().isEmpty()) section["LINE_TO"] = l.value("lineTo").toString();
        section["RANGE"] = QString::number(l.value("range", 20.0).toDouble());
        section["SPOT_SHARPNESS"] = QString::number(l.value("spotSharpness", 0.7).toDouble());
        section["FADE_AT"] = QString::number(l.value("fadeAt", 700).toDouble());
        section["FADE_SMOOTH"] = QString::number(l.value("fadeSmooth", 100).toDouble());
        section["DIFFUSE_CONCENTRATION"] = QString::number(l.value("diffuseConcentration", 0.5).toDouble());
        if (!l.value("color").toString().isEmpty()) section["COLOR"] = l.value("color").toString();
        if (!l.value("condition").toString().isEmpty()) section["CONDITION"] = l.value("condition").toString();
        result[name] = section;
    }
    return result;
}

// ── Serialize: Shader Replacements ───────────────────────────────────────────

QVariantMap CspConfigHandler::serializeShaderReplacements(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap r = items.at(i).toMap();
        QString name = r.value("sectionName").toString();
        if (name.isEmpty()) name = QString("SHADER_REPLACEMENT_%1").arg(i);
        QVariantMap section;
        if (!r.value("meshName").toString().isEmpty()) section["MESHES"] = r.value("meshName").toString();
        if (!r.value("materialName").toString().isEmpty()) section["MATERIALS"] = r.value("materialName").toString();
        if (!r.value("shader").toString().isEmpty()) section["SHADER"] = r.value("shader").toString();
        if (!r.value("blendMode").toString().isEmpty()) section["BLEND_MODE"] = r.value("blendMode").toString();
        if (!r.value("isTransparent").toString().isEmpty()) section["IS_TRANSPARENT"] = r.value("isTransparent").toString();
        if (!r.value("doubleFaceShadowBiased").toString().isEmpty()) section["DOUBLE_FACE_SHADOW_BIASED"] = r.value("doubleFaceShadowBiased").toString();
        QVariantList props = r.value("properties").toList();
        for (const QVariant& p : props) {
            QVariantMap pm = p.toMap();
            section[pm.value("key").toString()] = pm.value("value").toString();
        }
        result[name] = section;
    }
    return result;
}

// ── Serialize: Model Replacements ────────────────────────────────────────────

QVariantMap CspConfigHandler::serializeModelReplacements(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap r = items.at(i).toMap();
        QString name = r.value("sectionName").toString();
        if (name.isEmpty()) name = QString("MODEL_REPLACEMENT_%1").arg(i);
        QVariantMap section;
        if (!r.value("file").toString().isEmpty()) section["FILE"] = r.value("file").toString();
        if (!r.value("insert").toString().isEmpty()) section["INSERT"] = r.value("insert").toString();
        if (!r.value("insertAfter").toString().isEmpty()) section["INSERT_AFTER"] = r.value("insertAfter").toString();
        result[name] = section;
    }
    return result;
}

// ── Serialize: Includes ──────────────────────────────────────────────────────

QVariantMap CspConfigHandler::serializeIncludes(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap inc = items.at(i).toMap();
        QString name = inc.value("sectionName").toString();
        if (name.isEmpty()) name = QString("INCLUDE_%1").arg(i);
        QVariantMap section;
        section["INCLUDE"] = inc.value("include").toString();
        result[name] = section;
    }
    return result;
}

// ── Serialize: Emissives ─────────────────────────────────────────────────────

QVariantMap CspConfigHandler::serializeEmissives(const QVariantList& items) {
    QVariantMap result;
    for (int i = 0; i < items.size(); ++i) {
        QVariantMap e = items.at(i).toMap();
        QString name = e.value("sectionName").toString();
        if (name.isEmpty()) name = QString("EMISSIVE_%1").arg(i);
        QVariantMap section;
        if (!e.value("name").toString().isEmpty()) section["NAME"] = e.value("name").toString();
        if (!e.value("meshName").toString().isEmpty()) section["MESHES"] = e.value("meshName").toString();
        if (!e.value("materialName").toString().isEmpty()) section["MATERIALS"] = e.value("materialName").toString();
        if (!e.value("color").toString().isEmpty()) section["COLOR"] = e.value("color").toString();
        if (!e.value("colorOff").toString().isEmpty()) section["OFF_COLOR"] = e.value("colorOff").toString();
        if (!e.value("location").toString().isEmpty()) section["LOCATION"] = e.value("location").toString();
        if (!e.value("channel").toString().isEmpty()) section["CHANNEL"] = e.value("channel").toString();
        section["LAG"] = QString::number(e.value("lag", 0.0).toDouble());
        section["SIMULATE_HEATING"] = QString::number(e.value("simulateHeating", 0.0).toDouble());
        section["BIND_TO_HEADLIGHTS"] = e.value("bindToHeadlights", false).toBool() ? "1" : "0";
        section["ACTIVE"] = e.value("active", true).toBool() ? "1" : "0";
        if (!e.value("condition").toString().isEmpty()) section["CONDITION"] = e.value("condition").toString();
        result[name] = section;
    }
    return result;
}

// ── Serialize: Brake Discs ───────────────────────────────────────────────────

QVariantMap CspConfigHandler::serializeBrakeDiscs(const QVariantList& items) {
    QVariantMap result;
    for (const QVariant& v : items) {
        QVariantMap d = v.toMap();
        QString position = d.value("position").toString();
        QString name = d.value("sectionName").toString();
        if (name.isEmpty()) {
            if (position == "front") name = "BRAKEDISC_FX_FRONT";
            else if (position == "rear") name = "BRAKEDISC_FX_REAR";
            else name = "BRAKEDISC_FX";
        }
        QVariantMap section;
        section["AMBIENT_MULT"] = QString::number(d.value("ambientMult", 0.6).toDouble());
        section["REFLECTION_MULT"] = QString::number(d.value("reflectionMult", 1.0).toDouble());
        section["DISC_INTERNAL_RADIUS"] = QString::number(d.value("discInternalRadius", 0.126).toDouble());
        section["RIM_INTERNAL_RADIUS"] = QString::number(d.value("rimInternalRadius", 0.06).toDouble());
        result[name] = section;
    }
    return result;
}

// ── Editing API ──────────────────────────────────────────────────────────────

QVariantMap CspConfigHandler::addSection(QVariantMap sections, const QString& type, const QVariantMap& data) {
    QString name = generateSectionName(type, sections);
    QVariantMap section;
    for (auto it = data.constBegin(); it != data.constEnd(); ++it) {
        if (it.key() == "sectionName") continue;
        section[it.key()] = it.value();
    }
    sections[name] = section;
    return sections;
}

QVariantMap CspConfigHandler::removeSection(QVariantMap sections, const QString& sectionName) {
    sections.remove(sectionName);
    return sections;
}

QVariantMap CspConfigHandler::updateSection(QVariantMap sections, const QString& sectionName, const QVariantMap& data) {
    if (!sections.contains(sectionName)) return sections;
    QVariantMap section = sections[sectionName].toMap();
    for (auto it = data.constBegin(); it != data.constEnd(); ++it) {
        if (it.key() == "sectionName") continue;
        section[it.key()] = it.value();
    }
    sections[sectionName] = section;
    return sections;
}

// ── Shader compilation ──────────────────────────────────────────────────────

QVariantMap CspConfigHandler::compileShader(const QString& source, bool isFragment,
                                             const QString& entryPoint) {
    ShaderCompileResult result = CspShaderCompiler::compileGLSL(source, isFragment, entryPoint);
    QVariantMap map;
    map["success"] = result.success;
    map["spirvSize"] = result.spirv.size();
    map["compiler"] = result.compilerUsed;
    map["errors"] = QVariant::fromValue(result.errors);
    return map;
}

QVariantMap CspConfigHandler::profileShader(const QString& source) {
    ShaderProfile profile = CspShaderCompiler::profileShader(source);
    QVariantMap map;
    map["estimatedInstructions"] = profile.estimatedInstructions;
    map["textureSamples"] = profile.textureSamples;
    map["uniformCount"] = profile.uniformCount;
    map["inputCount"] = profile.inputCount;
    map["outputCount"] = profile.outputCount;
    map["branchCount"] = profile.branchCount;
    map["loopCount"] = profile.loopCount;
    map["functionCalls"] = profile.functionCalls;
    map["usesDiscard"] = profile.usesDiscard;
    map["usesDerivatives"] = profile.usesDerivatives;
    map["estimatedComplexity"] = profile.estimatedComplexity;
    map["summary"] = profile.summary();
    emit shaderProfileReady(profile.name, map);
    return map;
}

QStringList CspConfigHandler::compileShaderReplacement(const QVariantMap& sections,
                                                         const QString& sectionName) {
    QStringList errors;
    if (!sections.contains(sectionName)) {
        errors << "Section not found: " + sectionName;
        return errors;
    }

    QVariantMap section = sections[sectionName].toMap();
    QString source;
    if (section.contains("SOURCE")) {
        source = section["SOURCE"].toString();
    } else if (section.contains("FILE")) {
        QFile f(section["FILE"].toString());
        if (f.open(QIODevice::ReadOnly | QIODevice::Text))
            source = QString::fromUtf8(f.readAll());
    }

    if (source.isEmpty()) {
        errors << "No shader source found in " + sectionName;
        return errors;
    }

    bool isFragment = sectionName.contains("PS", Qt::CaseInsensitive) ||
                      sectionName.contains("PIXEL", Qt::CaseInsensitive) ||
                      sectionName.contains("FRAG", Qt::CaseInsensitive);

    ShaderCompileResult result = CspShaderCompiler::compileGLSL(source, isFragment);
    if (!result.success) {
        errors = result.errors;
    }

    emit shaderCompiled(sectionName, result.success);
    return errors;
}

QVariantList CspConfigHandler::profileShaderReplacements(const QVariantMap& sections) {
    QVariantList profiles;
    QStringList shaderSections = findSectionsByType(sections, "SHADER_REPLACEMENT");

    for (const QString& name : shaderSections) {
        QVariantMap section = sections[name].toMap();
        QString source = section.value("SOURCE", section.value("FILE", "")).toString();

        if (!source.isEmpty()) {
            ShaderProfile profile = CspShaderCompiler::profileShader(source);
            QVariantMap p;
            p["name"] = name;
            p["estimatedInstructions"] = profile.estimatedInstructions;
            p["textureSamples"] = profile.textureSamples;
            p["estimatedComplexity"] = profile.estimatedComplexity;
            p["summary"] = profile.summary();
            profiles.append(p);
        }
    }
    return profiles;
}

bool CspConfigHandler::saveCompiledShader(const QVariantMap& sections, const QString& sectionName, const QString& outputDir) {
    if (!sections.contains(sectionName)) return false;

    QVariantMap section = sections[sectionName].toMap();
    QString source = section.value("SOURCE", section.value("FILE", "")).toString();
    if (source.isEmpty()) return false;

    bool isFragment = sectionName.contains("PS", Qt::CaseInsensitive) ||
                      sectionName.contains("PIXEL", Qt::CaseInsensitive) ||
                      sectionName.contains("FRAG", Qt::CaseInsensitive);

    ShaderCompileResult result = CspShaderCompiler::compileGLSL(source, isFragment);
    if (!result.success) return false;

    QDir dir(outputDir);
    if (!dir.exists()) dir.mkpath(".");
    QString outPath = dir.filePath(sectionName + ".spv");
    QFile f(outPath);
    if (!f.open(QIODevice::WriteOnly)) return false;
    f.write(result.spirv);
    f.close();
    return true;
}

QStringList CspConfigHandler::findAvailableCompilers() {
    return CspShaderCompiler::findAvailableCompilers();
}

}
