#include "FfbConfigTool.h"
#include <QFile>
#include <QTextStream>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QStandardPaths>
#include <QDebug>
#include <QFileInfo>
#include <QDir>

namespace ks {

// ============================================================================
// FfbConfigTool Implementation
// ============================================================================

FfbConfigTool::FfbSettings FfbConfigTool::loadSettings(const QString& settingsPath) {
    FfbSettings settings;
    QFile file(settingsPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return settings; // Return defaults
    }
    
    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith(';') || line.startsWith('#') || line.startsWith('['))
            continue;
        
        int eq = line.indexOf('=');
        if (eq > 0) {
            QString key = line.left(eq).trimmed().toUpper();
            QString value = line.mid(eq + 1).trimmed();
            
            float val = value.toFloat();
            if (key == "GAIN") settings.gain = val;
            else if (key == "FILTER") settings.filter = val;
            else if (key == "MINIMUMFORCE") settings.minimumForce = val;
            else if (key == "KERBEFFECT") settings.kerbEffect = val;
            else if (key == "ROADEFFECT") settings.roadEffect = val;
            else if (key == "SLIPEFFECT") settings.slipEffect = val;
            else if (key == "ABSEFFECT") settings.absEffect = val;
            else if (key == "ENHUNDERSTEER") settings.enhUndersteer = val;
            else if (key == "CENTREBOOSTGAIN") settings.centreBoostGain = val;
            else if (key == "CENTREBOOSTRANGE") settings.centreBoostRange = val;
            else if (key == "ENABLEGYRO") settings.enableGyro = (value.toInt() != 0);
            else if (key == "GYROSTRENGTH") settings.gyroStrength = val;
        }
    }
    
    return settings;
}

bool FfbConfigTool::saveSettings(const FfbSettings& settings, const QString& settingsPath) {
    QFile file(settingsPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }
    
    QTextStream out(&file);
    out << "; FFB Settings generated by ksEditor\n";
    out << "[FORCE_FEEDBACK]\n";
    out << "GAIN=" << settings.gain << "\n";
    out << "FILTER=" << settings.filter << "\n";
    out << "MINIMUMFORCE=" << settings.minimumForce << "\n";
    out << "KERBEFFECT=" << settings.kerbEffect << "\n";
    out << "ROADEFFECT=" << settings.roadEffect << "\n";
    out << "SLIPEFFECT=" << settings.slipEffect << "\n";
    out << "ABSEFFECT=" << settings.absEffect << "\n";
    out << "ENHUNDERSTEER=" << settings.enhUndersteer << "\n";
    out << "CENTREBOOSTGAIN=" << settings.centreBoostGain << "\n";
    out << "CENTREBOOSTRANGE=" << settings.centreBoostRange << "\n";
    out << "ENABLEGYRO=" << (settings.enableGyro ? "1" : "0") << "\n";
    out << "GYROSTRENGTH=" << settings.gyroStrength << "\n";
    out << "\n";
    
    return true;
}

QVector<FfbConfigTool::WheelPreset> FfbConfigTool::getPresets() {
    return {
        getLogitechG27Preset(),
        getLogitechG29Preset(),
        getThrustmasterT300Preset(),
        getThrustmasterT818Preset(),
        getFanatecCSLPreset(),
        getFanatecCSW25Preset(),
        getSimucubePreset()
    };
}

FfbConfigTool::WheelPreset FfbConfigTool::getPreset(const QString& presetName) {
    for (const auto& preset : getPresets()) {
        if (preset.name == presetName) return preset;
    }
    return WheelPreset();
}

bool FfbConfigTool::applyPreset(FfbSettings& settings, const WheelPreset& preset) {
    settings = preset.settings;
    return true;
}

bool FfbConfigTool::savePreset(const WheelPreset& preset) {
    QString presetPath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + "/ffb_presets/" + preset.name + ".json";
    QDir().mkpath(QFileInfo(presetPath).absolutePath());
    
    QFile file(presetPath);
    if (!file.open(QIODevice::WriteOnly)) return false;
    
    QJsonObject obj;
    obj["name"] = preset.name;
    obj["wheelModel"] = preset.wheelModel;
    obj["manufacturer"] = preset.manufacturer;
    obj["description"] = preset.description;
    obj["isBuiltIn"] = preset.isBuiltIn;
    
    QJsonObject settings;
    settings["gain"] = preset.settings.gain;
    settings["filter"] = preset.settings.filter;
    settings["minimumForce"] = preset.settings.minimumForce;
    settings["kerbEffect"] = preset.settings.kerbEffect;
    settings["roadEffect"] = preset.settings.roadEffect;
    settings["slipEffect"] = preset.settings.slipEffect;
    settings["absEffect"] = preset.settings.absEffect;
    settings["enhUndersteer"] = preset.settings.enhUndersteer;
    settings["centreBoostGain"] = preset.settings.centreBoostGain;
    settings["centreBoostRange"] = preset.settings.centreBoostRange;
    settings["enableGyro"] = preset.settings.enableGyro;
    settings["gyroStrength"] = preset.settings.gyroStrength;
    obj["settings"] = settings;
    
    QJsonDocument doc(obj);
    file.write(doc.toJson(QJsonDocument::Indented));
    return true;
}

FfbConfigTool::WheelPreset FfbConfigTool::getLogitechG27Preset() {
    WheelPreset p;
    p.name = "Logitech G27";
    p.wheelModel = "G27";
    p.manufacturer = "Logitech";
    p.description = "Official Logitech G27 recommended settings";
    p.isBuiltIn = true;
    p.settings.gain = 100;
    p.settings.filter = 0;
    p.settings.minimumForce = 5;
    p.settings.kerbEffect = 100;
    p.settings.roadEffect = 80;
    p.settings.slipEffect = 60;
    p.settings.absEffect = 40;
    p.settings.enhUndersteer = 20;
    p.settings.centreBoostGain = 10;
    p.settings.centreBoostRange = 50;
    p.settings.enableGyro = false;
    p.settings.gyroStrength = 0;
    return p;
}

FfbConfigTool::WheelPreset FfbConfigTool::getLogitechG29Preset() {
    WheelPreset p;
    p.name = "Logitech G29/G920";
    p.wheelModel = "G29/G920";
    p.manufacturer = "Logitech";
    p.description = "Official Logitech G29/G920 recommended settings";
    p.isBuiltIn = true;
    p.settings.gain = 100;
    p.settings.filter = 0;
    p.settings.minimumForce = 5;
    p.settings.kerbEffect = 100;
    p.settings.roadEffect = 80;
    p.settings.slipEffect = 60;
    p.settings.absEffect = 40;
    p.settings.enhUndersteer = 20;
    p.settings.centreBoostGain = 10;
    p.settings.centreBoostRange = 50;
    p.settings.enableGyro = false;
    p.settings.gyroStrength = 0;
    return p;
}

FfbConfigTool::WheelPreset FfbConfigTool::getThrustmasterT300Preset() {
    WheelPreset p;
    p.name = "Thrustmaster T300 RS";
    p.wheelModel = "T300 RS";
    p.manufacturer = "Thrustmaster";
    p.description = "Thrustmaster T300 RS recommended settings";
    p.isBuiltIn = true;
    p.settings.gain = 75;
    p.settings.filter = 2;
    p.settings.minimumForce = 10;
    p.settings.kerbEffect = 80;
    p.settings.roadEffect = 70;
    p.settings.slipEffect = 50;
    p.settings.absEffect = 30;
    p.settings.enhUndersteer = 15;
    p.settings.centreBoostGain = 5;
    p.settings.centreBoostRange = 40;
    p.settings.enableGyro = false;
    p.settings.gyroStrength = 0;
    return p;
}

FfbConfigTool::WheelPreset FfbConfigTool::getThrustmasterT818Preset() {
    WheelPreset p;
    p.name = "Thrustmaster T818";
    p.wheelModel = "T818";
    p.manufacturer = "Thrustmaster";
    p.description = "Thrustmaster T818 recommended settings";
    p.isBuiltIn = true;
    p.settings.gain = 70;
    p.settings.filter = 2;
    p.settings.minimumForce = 10;
    p.settings.kerbEffect = 70;
    p.settings.roadEffect = 60;
    p.settings.slipEffect = 40;
    p.settings.absEffect = 30;
    p.settings.enhUndersteer = 10;
    p.settings.centreBoostGain = 5;
    p.settings.centreBoostRange = 35;
    p.settings.enableGyro = false;
    p.settings.gyroStrength = 0;
    return p;
}

FfbConfigTool::WheelPreset FfbConfigTool::getFanatecCSLPreset() {
    WheelPreset p;
    p.name = "Fanatec CSL DD";
    p.wheelModel = "CSL DD";
    p.manufacturer = "Fanatec";
    p.description = "Fanatec CSL DD recommended settings";
    p.isBuiltIn = true;
    p.settings.gain = 60;
    p.settings.filter = 3;
    p.settings.minimumForce = 5;
    p.settings.kerbEffect = 60;
    p.settings.roadEffect = 50;
    p.settings.slipEffect = 40;
    p.settings.absEffect = 20;
    p.settings.enhUndersteer = 10;
    p.settings.centreBoostGain = 5;
    p.settings.centreBoostRange = 30;
    p.settings.enableGyro = false;
    p.settings.gyroStrength = 0;
    return p;
}

FfbConfigTool::WheelPreset FfbConfigTool::getFanatecCSW25Preset() {
    WheelPreset p;
    p.name = "Fanatec CSW 2.5";
    p.wheelModel = "CSW 2.5";
    p.manufacturer = "Fanatec";
    p.description = "Fanatec CSW 2.5 recommended settings";
    p.isBuiltIn = true;
    p.settings.gain = 70;
    p.settings.filter = 2;
    p.settings.minimumForce = 5;
    p.settings.kerbEffect = 70;
    p.settings.roadEffect = 60;
    p.settings.slipEffect = 50;
    p.settings.absEffect = 25;
    p.settings.enhUndersteer = 15;
    p.settings.centreBoostGain = 5;
    p.settings.centreBoostRange = 35;
    p.settings.enableGyro = false;
    p.settings.gyroStrength = 0;
    return p;
}

FfbConfigTool::WheelPreset FfbConfigTool::getSimucubePreset() {
    WheelPreset p;
    p.name = "Simucube 2 Pro";
    p.wheelModel = "Simucube 2 Pro";
    p.manufacturer = "Simucube";
    p.description = "Simucube 2 Pro recommended settings";
    p.isBuiltIn = true;
    p.settings.gain = 50;
    p.settings.filter = 5;
    p.settings.minimumForce = 3;
    p.settings.kerbEffect = 40;
    p.settings.roadEffect = 40;
    p.settings.slipEffect = 30;
    p.settings.absEffect = 15;
    p.settings.enhUndersteer = 5;
    p.settings.centreBoostGain = 3;
    p.settings.centreBoostRange = 25;
    p.settings.enableGyro = false;
    p.settings.gyroStrength = 0;
    return p;
}

float FfbConfigTool::calculateOptimalGain(const FfbSettings& settings) {
    // Simplified calculation based on wheel type and settings
    float baseGain = settings.gain;
    float filterFactor = 1.0f - (settings.filter / 100.0f) * 0.5f;
    return baseGain * filterFactor;
}

float FfbConfigTool::calculateOptimalFilter(const FfbSettings& settings) {
    // Filter recommendation based on gain and wheel type
    if (settings.gain > 80) return 5.0f;
    if (settings.gain > 60) return 3.0f;
    return 1.0f;
}

void FfbConfigTool::optimizeForWheel(FfbSettings& settings, const QString& wheelModel) {
    if (wheelModel.contains("G27", Qt::CaseInsensitive) || wheelModel.contains("G29", Qt::CaseInsensitive)) {
        settings = getLogitechG29Preset().settings;
    } else if (wheelModel.contains("T300", Qt::CaseInsensitive)) {
        settings = getThrustmasterT300Preset().settings;
    } else if (wheelModel.contains("T818", Qt::CaseInsensitive)) {
        settings = getThrustmasterT818Preset().settings;
    } else if (wheelModel.contains("CSL DD", Qt::CaseInsensitive) || wheelModel.contains("CSL", Qt::CaseInsensitive)) {
        settings = getFanatecCSLPreset().settings;
    } else if (wheelModel.contains("CSW", Qt::CaseInsensitive)) {
        settings = getFanatecCSW25Preset().settings;
    } else if (wheelModel.contains("Simucube", Qt::CaseInsensitive)) {
        settings = getSimucubePreset().settings;
    }
}

bool FfbConfigTool::validateSettings(const FfbSettings& settings, QString* error) {
    if (settings.gain < 0 || settings.gain > 100) {
        if (error) *error = "Gain must be 0-100";
        return false;
    }
    if (settings.filter < 0 || settings.filter > 100) {
        if (error) *error = "Filter must be 0-100";
        return false;
    }
    if (settings.minimumForce < 0 || settings.minimumForce > 100) {
        if (error) *error = "Minimum force must be 0-100";
        return false;
    }
    if (settings.kerbEffect < 0 || settings.kerbEffect > 100) {
        if (error) *error = "Kerb effect must be 0-100";
        return false;
    }
    if (settings.roadEffect < 0 || settings.roadEffect > 100) {
        if (error) *error = "Road effect must be 0-100";
        return false;
    }
    if (settings.slipEffect < 0 || settings.slipEffect > 100) {
        if (error) *error = "Slip effect must be 0-100";
        return false;
    }
    if (settings.absEffect < 0 || settings.absEffect > 100) {
        if (error) *error = "ABS effect must be 0-100";
        return false;
    }
    if (settings.enhUndersteer < 0 || settings.enhUndersteer > 100) {
        if (error) *error = "Enhanced understeer must be 0-100";
        return false;
    }
    if (settings.centreBoostGain < 0 || settings.centreBoostGain > 100) {
        if (error) *error = "Centre boost gain must be 0-100";
        return false;
    }
    if (settings.centreBoostRange < 0 || settings.centreBoostRange > 100) {
        if (error) *error = "Centre boost range must be 0-100";
        return false;
    }
    if (settings.gyroStrength < 0 || settings.gyroStrength > 100) {
        if (error) *error = "Gyro strength must be 0-100";
        return false;
    }
    return true;
}

QString FfbConfigTool::getWheelManufacturer(const QString& wheelModel) {
    static QMap<QString, QString> manufacturers = {
        {"G27", "Logitech"}, {"G29", "Logitech"}, {"G920", "Logitech"}, {"G923", "Logitech"},
        {"T150", "Thrustmaster"}, {"T300", "Thrustmaster"}, {"T500", "Thrustmaster"}, {"T818", "Thrustmaster"},
        {"CSL", "Fanatec"}, {"CSW", "Fanatec"}, {"PODIUM", "Fanatec"},
        {"SIMUCUBE", "Simucube"}, {"SIMUCUBE", "Simucube"},
        {"MOZA", "Moza"}, {"ALPHA", "Alpha"},
    };
    
    for (auto it = manufacturers.begin(); it != manufacturers.end(); ++it) {
        if (wheelModel.contains(it.key(), Qt::CaseInsensitive)) {
            return it.value();
        }
    }
    return "Unknown";
}

QStringList FfbConfigTool::getSupportedWheels() {
    return {
        "Logitech G27", "Logitech G29", "Logitech G920", "Logitech G923",
        "Thrustmaster T150", "Thrustmaster T300 RS", "Thrustmaster T500 RS", "Thrustmaster T818",
        "Fanatec CSL DD", "Fanatec CSL Elite", "Fanatec CSW 2.5", "Fanatec Podium DD1", "Fanatec Podium DD2",
        "Simucube 2 Pro", "Simucube 2 Sport", "Simucube 2 Ultimate",
        "Moza R9", "Moza R12", "Moza R16",
        "Alpha Mini"
    };
}

// ============================================================================
// FfbConfigManager Implementation
// ============================================================================

FfbConfigManager::FfbConfigManager(const QString& acPath) : m_acPath(acPath) {
}

bool FfbConfigManager::loadSettings() {
    QString settingsPath = m_acPath + "/cfg/ff_post_process.ini";
    m_settings = FfbConfigTool::loadSettings(settingsPath);
    return true;
}

bool FfbConfigManager::saveSettings() {
    QString settingsPath = m_acPath + "/cfg/ff_post_process.ini";
    return FfbConfigTool::saveSettings(m_settings, settingsPath);
}

bool FfbConfigManager::applyPreset(const QString& presetName) {
    for (const auto& preset : FfbConfigTool::getPresets()) {
        if (preset.name == presetName) {
            m_settings = preset.settings;
            return saveSettings();
        }
    }
    return false;
}

bool FfbConfigManager::optimizeForWheel(const QString& wheelModel) {
    FfbConfigTool::optimizeForWheel(m_settings, wheelModel);
    return saveSettings();
}

} // namespace ks