#include "CarSetupEditor.h"
#include <QFile>
#include <QTextStream>
#include <QDir>
#include <QJsonDocument>
#include <QJsonObject>
#include <QDebug>

// ============================================================================
// File operations
// ============================================================================

CarSetupEditor::CarSetup CarSetupEditor::loadSetup(const QString& setupPath) {
    CarSetup setup;

    QString iniPath = setupPath;
    if (!setupPath.endsWith(".ini")) {
        iniPath = setupPath + "/setup.ini";
    }

    loadFromIni(setup, iniPath);
    return setup;
}

bool CarSetupEditor::saveSetup(const CarSetup& setup, const QString& setupPath) {
    QString iniPath = setupPath;
    if (!setupPath.endsWith(".ini")) {
        QDir().mkpath(setupPath);
        iniPath = setupPath + "/setup.ini";
    }

    return saveToIni(setup, iniPath);
}

bool CarSetupEditor::loadFromIni(CarSetup& setup, const QString& iniPath) {
    QFile file(iniPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    QString currentSection;
    QMap<QString, QString> currentKeys;

    while (!stream.atEnd()) {
        QString line = stream.readLine().trimmed();

        // Skip comments and empty lines
        if (line.startsWith(';') || line.startsWith('#') || line.isEmpty()) {
            continue;
        }

        // Section header
        if (line.startsWith('[') && line.endsWith(']')) {
            // Parse previous section
            if (!currentSection.isEmpty()) {
                parseSection(currentSection, currentKeys, setup);
            }

            currentSection = line.mid(1, line.length() - 2);
            currentKeys.clear();
            continue;
        }

        // Key-value pair
        if (line.contains('=')) {
            int eqPos = line.indexOf('=');
            QString key = line.left(eqPos).trimmed();
            QString value = line.mid(eqPos + 1).trimmed();
            currentKeys[key] = value;
        }
    }

    // Parse last section
    if (!currentSection.isEmpty()) {
        parseSection(currentSection, currentKeys, setup);
    }

    file.close();
    return true;
}

bool CarSetupEditor::saveToIni(const CarSetup& setup, const QString& iniPath) {
    QFile file(iniPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    stream << "; Car Setup Configuration\n";
    stream << "; Generated by ksEditor\n\n";

    // Brakes
    stream << "[BRAKES]\n";
    stream << "FRONT_BIAS=" << QString::number(setup.brakes.frontBrakeBias, 'f', 2) << "\n";
    stream << "PRESSURE=" << QString::number(setup.brakes.brakePressure, 'f', 2) << "\n";
    stream << "PAD_COMPOUND=" << QString::number(setup.brakes.brakePadCompound, 'f', 2) << "\n";
    stream << "DUCT_OPENING=" << QString::number(setup.brakes.brakeDuctOpening, 'f', 2) << "\n";
    stream << "FRONT_POWER_L=" << QString::number(setup.brakes.frontBrakePower[0], 'f', 4) << "\n";
    stream << "FRONT_POWER_R=" << QString::number(setup.brakes.frontBrakePower[1], 'f', 4) << "\n";
    stream << "REAR_POWER_L=" << QString::number(setup.brakes.rearBrakePower[0], 'f', 4) << "\n";
    stream << "REAR_POWER_R=" << QString::number(setup.brakes.rearBrakePower[1], 'f', 4) << "\n\n";

    // Suspension
    stream << "[SUSPENSION]\n";
    stream << "FRONT_SPRING_L=" << QString::number(setup.suspension.frontSpringRate[0], 'f', 2) << "\n";
    stream << "FRONT_SPRING_R=" << QString::number(setup.suspension.frontSpringRate[1], 'f', 2) << "\n";
    stream << "REAR_SPRING_L=" << QString::number(setup.suspension.rearSpringRate[0], 'f', 2) << "\n";
    stream << "REAR_SPRING_R=" << QString::number(setup.suspension.rearSpringRate[1], 'f', 2) << "\n";
    stream << "FRONT_BUMP_L=" << QString::number(setup.suspension.frontBumpDamper[0], 'f', 0) << "\n";
    stream << "FRONT_BUMP_R=" << QString::number(setup.suspension.frontBumpDamper[1], 'f', 0) << "\n";
    stream << "FRONT_REBOUND_L=" << QString::number(setup.suspension.frontReboundDamper[0], 'f', 0) << "\n";
    stream << "FRONT_REBOUND_R=" << QString::number(setup.suspension.frontReboundDamper[1], 'f', 0) << "\n";
    stream << "REAR_BUMP_L=" << QString::number(setup.suspension.rearBumpDamper[0], 'f', 0) << "\n";
    stream << "REAR_BUMP_R=" << QString::number(setup.suspension.rearBumpDamper[1], 'f', 0) << "\n";
    stream << "REAR_REBOUND_L=" << QString::number(setup.suspension.rearReboundDamper[0], 'f', 0) << "\n";
    stream << "REAR_REBOUND_R=" << QString::number(setup.suspension.rearReboundDamper[1], 'f', 0) << "\n";
    stream << "FRONT_RIDE_HEIGHT=" << QString::number(setup.suspension.frontRideHeight, 'f', 2) << "\n";
    stream << "REAR_RIDE_HEIGHT=" << QString::number(setup.suspension.rearRideHeight, 'f', 2) << "\n";
    stream << "FRONT_ARB=" << QString::number(setup.suspension.frontARB, 'f', 2) << "\n";
    stream << "REAR_ARB=" << QString::number(setup.suspension.rearARB, 'f', 2) << "\n";
    stream << "FRONT_BUMP_STOP=" << QString::number(setup.suspension.frontBumpStopRate, 'f', 0) << "\n";
    stream << "REAR_BUMP_STOP=" << QString::number(setup.suspension.rearBumpStopRate, 'f', 0) << "\n\n";

    // Tyres
    stream << "[TYRES]\n";
    stream << "FRONT_PRESSURE_L=" << QString::number(setup.tyres.frontTyrePressure[0], 'f', 2) << "\n";
    stream << "FRONT_PRESSURE_R=" << QString::number(setup.tyres.frontTyrePressure[1], 'f', 2) << "\n";
    stream << "REAR_PRESSURE_L=" << QString::number(setup.tyres.rearTyrePressure[0], 'f', 2) << "\n";
    stream << "REAR_PRESSURE_R=" << QString::number(setup.tyres.rearTyrePressure[1], 'f', 2) << "\n";
    stream << "FRONT_CAMBER_L=" << QString::number(setup.tyres.frontCamber[0], 'f', 2) << "\n";
    stream << "FRONT_CAMBER_R=" << QString::number(setup.tyres.frontCamber[1], 'f', 2) << "\n";
    stream << "REAR_CAMBER_L=" << QString::number(setup.tyres.rearCamber[0], 'f', 2) << "\n";
    stream << "REAR_CAMBER_R=" << QString::number(setup.tyres.rearCamber[1], 'f', 2) << "\n";
    stream << "FRONT_TOE_L=" << QString::number(setup.tyres.frontToe[0], 'f', 3) << "\n";
    stream << "FRONT_TOE_R=" << QString::number(setup.tyres.frontToe[1], 'f', 3) << "\n";
    stream << "REAR_TOE_L=" << QString::number(setup.tyres.rearToe[0], 'f', 3) << "\n";
    stream << "REAR_TOE_R=" << QString::number(setup.tyres.rearToe[1], 'f', 3) << "\n";
    stream << "FRONT_COMPOUND=" << setup.tyres.frontCompound << "\n";
    stream << "REAR_COMPOUND=" << setup.tyres.rearCompound << "\n\n";

    // Aero
    stream << "[AERO]\n";
    stream << "FRONT_WING=" << QString::number(setup.aero.frontWingAngle, 'f', 2) << "\n";
    stream << "REAR_WING=" << QString::number(setup.aero.rearWingAngle, 'f', 2) << "\n";
    stream << "SPLITTER_HEIGHT=" << QString::number(setup.aero.splitterHeight, 'f', 2) << "\n";
    stream << "DIFFUSER_ANGLE=" << QString::number(setup.aero.diffuserAngle, 'f', 2) << "\n";
    stream << "FRONT_RIDE_TARGET=" << QString::number(setup.aero.frontRideHeightTarget, 'f', 2) << "\n";
    stream << "REAR_RIDE_TARGET=" << QString::number(setup.aero.rearRideHeightTarget, 'f', 2) << "\n\n";

    // Differential
    stream << "[DIFFERENTIAL]\n";
    stream << "PRELOAD=" << QString::number(setup.differential.preload, 'f', 2) << "\n";
    stream << "COAST_POWER=" << QString::number(setup.differential.coastPower, 'f', 4) << "\n";
    stream << "DRIVE_POWER=" << QString::number(setup.differential.drivePower, 'f', 4) << "\n";
    stream << "COAST_BRAKE=" << QString::number(setup.differential.coastBrake, 'f', 4) << "\n";
    stream << "DRIVE_BRAKE=" << QString::number(setup.differential.driveBrake, 'f', 4) << "\n";
    stream << "CENTRAL_DIFF=" << QString::number(setup.differential.centralDifferential, 'f', 4) << "\n\n";

    // Electronics
    stream << "[ELECTRONICS]\n";
    stream << "TC=" << QString::number(setup.electronics.tractionControl, 'f', 2) << "\n";
    stream << "ABS=" << QString::number(setup.electronics.abs, 'f', 2) << "\n";
    stream << "ECU_MAP=" << setup.electronics.ecuMap << "\n";
    stream << "AUTO_BLIP=" << (setup.electronics.autoBlip ? "1" : "0") << "\n";
    stream << "AUTO_BRAKE=" << (setup.electronics.autoBrake ? "1" : "0") << "\n\n";

    // Engine
    stream << "[ENGINE]\n";
    stream << "FUEL_CAPACITY=" << QString::number(setup.engine.fuelCapacity, 'f', 2) << "\n";
    stream << "FUEL_LOAD=" << QString::number(setup.engine.fuelLoad, 'f', 2) << "\n";
    stream << "ENGINE_BRAKE_MAP=" << setup.engine.engineBrakeMap << "\n";
    stream << "POWER_BOOST_MAP=" << setup.engine.powerBoostMap << "\n";

    file.close();
    return true;
}

// ============================================================================
// Setup management
// ============================================================================

QStringList CarSetupEditor::getAvailableSetups(const QString& carPath) {
    QStringList setups;

    QString setupsDir = carPath + "/setup";
    QDir dir(setupsDir);
    if (dir.exists()) {
        QFileInfoList files = dir.entryInfoList(QStringList() << "*.ini", QDir::Files);
        for (const QFileInfo& fileInfo : files) {
            setups.append(fileInfo.baseName());
        }
    }

    return setups;
}

CarSetupEditor::CarSetup CarSetupEditor::getSetup(const QString& carPath, const QString& setupName) {
    QString setupPath = carPath + "/setup/" + setupName + ".ini";
    return loadSetup(setupPath);
}

bool CarSetupEditor::deleteSetup(const QString& carPath, const QString& setupName) {
    QString setupPath = carPath + "/setup/" + setupName + ".ini";
    return QFile::remove(setupPath);
}

bool CarSetupEditor::copySetup(const QString& carPath, const QString& sourceName, const QString& destName) {
    QString sourcePath = carPath + "/setup/" + sourceName + ".ini";
    QString destPath = carPath + "/setup/" + destName + ".ini";
    return QFile::copy(sourcePath, destPath);
}

// ============================================================================
// Presets
// ============================================================================

CarSetupEditor::CarSetup CarSetupEditor::getQualifyingSetup() {
    CarSetup setup;
    setup.name = "Qualifying";

    // Soft tyres, low fuel, aggressive aero
    setup.tyres.frontTyrePressure[0] = setup.tyres.frontTyrePressure[1] = 27.0f;
    setup.tyres.rearTyrePressure[0] = setup.tyres.rearTyrePressure[1] = 25.0f;
    setup.tyres.frontCamber[0] = setup.tyres.frontCamber[1] = -3.8f;
    setup.tyres.rearCamber[0] = setup.tyres.rearCamber[1] = -2.2f;

    setup.engine.fuelLoad = 10.0f;

    setup.aero.frontWingAngle = 10.0f;
    setup.aero.rearWingAngle = 12.0f;

    setup.suspension.frontSpringRate[0] = setup.suspension.frontSpringRate[1] = 140.0f;
    setup.suspension.rearSpringRate[0] = setup.suspension.rearSpringRate[1] = 170.0f;

    return setup;
}

CarSetupEditor::CarSetup CarSetupEditor::getRaceSetup() {
    CarSetup setup;
    setup.name = "Race";

    // Medium tyres, full fuel, balanced aero
    setup.tyres.frontTyrePressure[0] = setup.tyres.frontTyrePressure[1] = 26.0f;
    setup.tyres.rearTyrePressure[0] = setup.tyres.rearTyrePressure[1] = 24.0f;
    setup.tyres.frontCamber[0] = setup.tyres.frontCamber[1] = -3.5f;
    setup.tyres.rearCamber[0] = setup.tyres.rearCamber[1] = -2.0f;

    setup.engine.fuelLoad = 100.0f;

    setup.aero.frontWingAngle = 8.0f;
    setup.aero.rearWingAngle = 10.0f;

    return setup;
}

CarSetupEditor::CarSetup CarSetupEditor::getWetSetup() {
    CarSetup setup;
    setup.name = "Wet";

    // Wet tyres, higher pressures, more downforce
    setup.tyres.frontTyrePressure[0] = setup.tyres.frontTyrePressure[1] = 28.0f;
    setup.tyres.rearTyrePressure[0] = setup.tyres.rearTyrePressure[1] = 26.0f;
    setup.tyres.frontCamber[0] = setup.tyres.frontCamber[1] = -2.5f;
    setup.tyres.rearCamber[0] = setup.tyres.rearCamber[1] = -1.5f;

    setup.aero.frontWingAngle = 12.0f;
    setup.aero.rearWingAngle = 14.0f;

    setup.suspension.frontSpringRate[0] = setup.suspension.frontSpringRate[1] = 130.0f;
    setup.suspension.rearSpringRate[0] = setup.suspension.rearSpringRate[1] = 160.0f;

    setup.brakes.brakePadCompound = 2.0f; // Wet compound

    return setup;
}

CarSetupEditor::CarSetup CarSetupEditor::getDriftSetup() {
    CarSetup setup;
    setup.name = "Drift";

    // Soft rear, stiff front for oversteer
    setup.tyres.frontTyrePressure[0] = setup.tyres.frontTyrePressure[1] = 25.0f;
    setup.tyres.rearTyrePressure[0] = setup.tyres.rearTyrePressure[1] = 22.0f;
    setup.tyres.frontCamber[0] = setup.tyres.frontCamber[1] = -4.0f;
    setup.tyres.rearCamber[0] = setup.tyres.rearCamber[1] = -1.0f;
    setup.tyres.frontToe[0] = setup.tyres.frontToe[1] = 0.3f;

    setup.suspension.frontSpringRate[0] = setup.suspension.frontSpringRate[1] = 160.0f;
    setup.suspension.rearSpringRate[0] = setup.suspension.rearSpringRate[1] = 140.0f;
    setup.suspension.frontARB = 35.0f;
    setup.suspension.rearARB = 20.0f;

    setup.differential.coastPower = 0.1f;
    setup.differential.drivePower = 0.8f;

    setup.electronics.tractionControl = 0.0f;

    return setup;
}

CarSetupEditor::CarSetup CarSetupEditor::getEnduranceSetup() {
    CarSetup setup;
    setup.name = "Endurance";

    // Durable setup, higher fuel, conservative
    setup.tyres.frontTyrePressure[0] = setup.tyres.frontTyrePressure[1] = 27.0f;
    setup.tyres.rearTyrePressure[0] = setup.tyres.rearTyrePressure[1] = 25.0f;
    setup.tyres.frontCamber[0] = setup.tyres.frontCamber[1] = -3.2f;
    setup.tyres.rearCamber[0] = setup.tyres.rearCamber[1] = -1.8f;

    setup.engine.fuelLoad = 120.0f;

    setup.aero.frontWingAngle = 9.0f;
    setup.aero.rearWingAngle = 11.0f;

    setup.suspension.frontSpringRate[0] = setup.suspension.frontSpringRate[1] = 155.0f;
    setup.suspension.rearSpringRate[0] = setup.suspension.rearSpringRate[1] = 185.0f;

    return setup;
}

// ============================================================================
// Comparison
// ============================================================================

QMap<QString, QPair<double, double>> CarSetupEditor::compareSetups(const CarSetup& a, const CarSetup& b) {
    QMap<QString, QPair<double, double>> differences;

    // Brakes
    differences["Brake Bias"] = {a.brakes.frontBrakeBias, b.brakes.frontBrakeBias};
    differences["Brake Pressure"] = {a.brakes.brakePressure, b.brakes.brakePressure};

    // Suspension
    differences["Front Spring Rate"] = {a.suspension.frontSpringRate[0], b.suspension.frontSpringRate[0]};
    differences["Rear Spring Rate"] = {a.suspension.rearSpringRate[0], b.suspension.rearSpringRate[0]};
    differences["Front Ride Height"] = {a.suspension.frontRideHeight, b.suspension.frontRideHeight};
    differences["Rear Ride Height"] = {a.suspension.rearRideHeight, b.suspension.rearRideHeight};
    differences["Front ARB"] = {a.suspension.frontARB, b.suspension.frontARB};
    differences["Rear ARB"] = {a.suspension.rearARB, b.suspension.rearARB};

    // Tyres
    differences["Front Pressure"] = {a.tyres.frontTyrePressure[0], b.tyres.frontTyrePressure[0]};
    differences["Rear Pressure"] = {a.tyres.rearTyrePressure[0], b.tyres.rearTyrePressure[0]};
    differences["Front Camber"] = {a.tyres.frontCamber[0], b.tyres.frontCamber[0]};
    differences["Rear Camber"] = {a.tyres.rearCamber[0], b.tyres.rearCamber[0]};

    // Aero
    differences["Front Wing"] = {a.aero.frontWingAngle, b.aero.frontWingAngle};
    differences["Rear Wing"] = {a.aero.rearWingAngle, b.aero.rearWingAngle};

    // Differential
    differences["Diff Preload"] = {a.differential.preload, b.differential.preload};
    differences["Diff Coast"] = {a.differential.coastPower, b.differential.coastPower};
    differences["Diff Drive"] = {a.differential.drivePower, b.differential.drivePower};

    // Electronics
    differences["TC"] = {a.electronics.tractionControl, b.electronics.tractionControl};
    differences["ABS"] = {a.electronics.abs, b.electronics.abs};

    // Engine
    differences["Fuel Load"] = {a.engine.fuelLoad, b.engine.fuelLoad};

    return differences;
}

// ============================================================================
// Validation
// ============================================================================

bool CarSetupEditor::validateSetup(const CarSetup& setup, QString* error) {
    // Brake validation
    if (setup.brakes.frontBrakeBias < 30.0f || setup.brakes.frontBrakeBias > 70.0f) {
        if (error) *error = "Brake bias out of range (30-70%)";
        return false;
    }

    if (setup.brakes.brakePressure < 50.0f || setup.brakes.brakePressure > 150.0f) {
        if (error) *error = "Brake pressure out of range (50-150%)";
        return false;
    }

    // Suspension validation
    if (setup.suspension.frontRideHeight < 20.0f || setup.suspension.frontRideHeight > 100.0f) {
        if (error) *error = "Front ride height out of range (20-100mm)";
        return false;
    }

    if (setup.suspension.rearRideHeight < 20.0f || setup.suspension.rearRideHeight > 100.0f) {
        if (error) *error = "Rear ride height out of range (20-100mm)";
        return false;
    }

    // Tyre validation
    for (int i = 0; i < 2; ++i) {
        if (setup.tyres.frontTyrePressure[i] < 15.0f || setup.tyres.frontTyrePressure[i] > 50.0f) {
            if (error) *error = "Front tyre pressure out of range (15-50 PSI)";
            return false;
        }

        if (setup.tyres.rearTyrePressure[i] < 15.0f || setup.tyres.rearTyrePressure[i] > 50.0f) {
            if (error) *error = "Rear tyre pressure out of range (15-50 PSI)";
            return false;
        }
    }

    // Aero validation
    if (setup.aero.frontWingAngle < 0.0f || setup.aero.frontWingAngle > 20.0f) {
        if (error) *error = "Front wing angle out of range (0-20 degrees)";
        return false;
    }

    if (setup.aero.rearWingAngle < 0.0f || setup.aero.rearWingAngle > 20.0f) {
        if (error) *error = "Rear wing angle out of range (0-20 degrees)";
        return false;
    }

    // Differential validation
    if (setup.differential.preload < 0.0f || setup.differential.preload > 100.0f) {
        if (error) *error = "Differential preload out of range (0-100 Nm)";
        return false;
    }

    // Electronics validation
    if (setup.electronics.tractionControl < 0.0f || setup.electronics.tractionControl > 10.0f) {
        if (error) *error = "TC out of range (0-10)";
        return false;
    }

    if (setup.electronics.abs < 0.0f || setup.electronics.abs > 10.0f) {
        if (error) *error = "ABS out of range (0-10)";
        return false;
    }

    // Engine validation
    if (setup.engine.fuelLoad < 0.0f || setup.engine.fuelLoad > setup.engine.fuelCapacity) {
        if (error) *error = "Fuel load exceeds capacity";
        return false;
    }

    return true;
}

// ============================================================================
// Utility
// ============================================================================

QString CarSetupEditor::getSetupTypeName(int type) {
    switch (type) {
        case 0: return "Practice";
        case 1: return "Qualifying";
        case 2: return "Race";
        default: return "Unknown";
    }
}

// ============================================================================
// Private helpers
// ============================================================================

void CarSetupEditor::parseSection(const QString& section, const QMap<QString, QString>& keys, CarSetup& setup) {
    if (section == "BRAKES") {
        setup.brakes.frontBrakeBias = keys.value("FRONT_BIAS", "56").toFloat();
        setup.brakes.brakePressure = keys.value("PRESSURE", "100").toFloat();
        setup.brakes.brakePadCompound = keys.value("PAD_COMPOUND", "1").toFloat();
        setup.brakes.brakeDuctOpening = keys.value("DUCT_OPENING", "1").toFloat();
    } else if (section == "SUSPENSION") {
        setup.suspension.frontSpringRate[0] = keys.value("FRONT_SPRING_L", "150").toFloat();
        setup.suspension.frontSpringRate[1] = keys.value("FRONT_SPRING_R", "150").toFloat();
        setup.suspension.rearSpringRate[0] = keys.value("REAR_SPRING_L", "180").toFloat();
        setup.suspension.rearSpringRate[1] = keys.value("REAR_SPRING_R", "180").toFloat();
        setup.suspension.frontBumpDamper[0] = keys.value("FRONT_BUMP_L", "0").toFloat();
        setup.suspension.frontBumpDamper[1] = keys.value("FRONT_BUMP_R", "0").toFloat();
        setup.suspension.frontReboundDamper[0] = keys.value("FRONT_REBOUND_L", "0").toFloat();
        setup.suspension.frontReboundDamper[1] = keys.value("FRONT_REBOUND_R", "0").toFloat();
        setup.suspension.rearBumpDamper[0] = keys.value("REAR_BUMP_L", "0").toFloat();
        setup.suspension.rearBumpDamper[1] = keys.value("REAR_BUMP_R", "0").toFloat();
        setup.suspension.rearReboundDamper[0] = keys.value("REAR_REBOUND_L", "0").toFloat();
        setup.suspension.rearReboundDamper[1] = keys.value("REAR_REBOUND_R", "0").toFloat();
        setup.suspension.frontRideHeight = keys.value("FRONT_RIDE_HEIGHT", "55").toFloat();
        setup.suspension.rearRideHeight = keys.value("REAR_RIDE_HEIGHT", "70").toFloat();
        setup.suspension.frontARB = keys.value("FRONT_ARB", "25").toFloat();
        setup.suspension.rearARB = keys.value("REAR_ARB", "30").toFloat();
        setup.suspension.frontBumpStopRate = keys.value("FRONT_BUMP_STOP", "0").toFloat();
        setup.suspension.rearBumpStopRate = keys.value("REAR_BUMP_STOP", "0").toFloat();
    } else if (section == "TYRES") {
        setup.tyres.frontTyrePressure[0] = keys.value("FRONT_PRESSURE_L", "26").toFloat();
        setup.tyres.frontTyrePressure[1] = keys.value("FRONT_PRESSURE_R", "26").toFloat();
        setup.tyres.rearTyrePressure[0] = keys.value("REAR_PRESSURE_L", "24").toFloat();
        setup.tyres.rearTyrePressure[1] = keys.value("REAR_PRESSURE_R", "24").toFloat();
        setup.tyres.frontCamber[0] = keys.value("FRONT_CAMBER_L", "-3.5").toFloat();
        setup.tyres.frontCamber[1] = keys.value("FRONT_CAMBER_R", "-3.5").toFloat();
        setup.tyres.rearCamber[0] = keys.value("REAR_CAMBER_L", "-2.0").toFloat();
        setup.tyres.rearCamber[1] = keys.value("REAR_CAMBER_R", "-2.0").toFloat();
        setup.tyres.frontToe[0] = keys.value("FRONT_TOE_L", "0").toFloat();
        setup.tyres.frontToe[1] = keys.value("FRONT_TOE_R", "0").toFloat();
        setup.tyres.rearToe[0] = keys.value("REAR_TOE_L", "0").toFloat();
        setup.tyres.rearToe[1] = keys.value("REAR_TOE_R", "0").toFloat();
        setup.tyres.frontCompound = keys.value("FRONT_COMPOUND", "0").toInt();
        setup.tyres.rearCompound = keys.value("REAR_COMPOUND", "0").toInt();
    } else if (section == "AERO") {
        setup.aero.frontWingAngle = keys.value("FRONT_WING", "8").toFloat();
        setup.aero.rearWingAngle = keys.value("REAR_WING", "10").toFloat();
        setup.aero.splitterHeight = keys.value("SPLITTER_HEIGHT", "30").toFloat();
        setup.aero.diffuserAngle = keys.value("DIFFUSER_ANGLE", "8").toFloat();
        setup.aero.frontRideHeightTarget = keys.value("FRONT_RIDE_TARGET", "0").toFloat();
        setup.aero.rearRideHeightTarget = keys.value("REAR_RIDE_TARGET", "0").toFloat();
    } else if (section == "DIFFERENTIAL") {
        setup.differential.preload = keys.value("PRELOAD", "20").toFloat();
        setup.differential.coastPower = keys.value("COAST_POWER", "0.3").toFloat();
        setup.differential.drivePower = keys.value("DRIVE_POWER", "0.5").toFloat();
        setup.differential.coastBrake = keys.value("COAST_BRAKE", "0").toFloat();
        setup.differential.driveBrake = keys.value("DRIVE_BRAKE", "0").toFloat();
        setup.differential.centralDifferential = keys.value("CENTRAL_DIFF", "0").toFloat();
    } else if (section == "ELECTRONICS") {
        setup.electronics.tractionControl = keys.value("TC", "0").toFloat();
        setup.electronics.abs = keys.value("ABS", "0").toFloat();
        setup.electronics.ecuMap = keys.value("ECU_MAP", "0").toInt();
        setup.electronics.autoBlip = (keys.value("AUTO_BLIP", "0") == "1");
        setup.electronics.autoBrake = (keys.value("AUTO_BRAKE", "0") == "1");
    } else if (section == "ENGINE") {
        setup.engine.fuelCapacity = keys.value("FUEL_CAPACITY", "100").toFloat();
        setup.engine.fuelLoad = keys.value("FUEL_LOAD", "50").toFloat();
        setup.engine.engineBrakeMap = keys.value("ENGINE_BRAKE_MAP", "0").toInt();
        setup.engine.powerBoostMap = keys.value("POWER_BOOST_MAP", "0").toInt();
    }
}
