#include "ServerConfigEditor.h"
#include <QFile>
#include <QTextStream>
#include <QDir>
#include <QRegularExpression>
#include <QDebug>
#include "core/editor/EditorConfig.h"

// ============================================================================
// Config operations
// ============================================================================

ServerConfigEditor::ServerConfig ServerConfigEditor::loadConfig(const QString& serverPath) {
    ServerConfig config;

    // Load main config
    QString iniPath = serverPath + "/cfg/server_cfg.ini";
    if (QFile::exists(iniPath)) {
        loadFromIni(config, iniPath);
    }

    // Load extra/CSP config
    QString extraPath = serverPath + "/cfg/extra_cfg.yml";
    if (QFile::exists(extraPath)) {
        loadExtraConfig(config, serverPath);
    }

    return config;
}

bool ServerConfigEditor::saveConfig(const ServerConfig& config, const QString& serverPath) {
    // Save main config
    QString iniPath = serverPath + "/cfg/server_cfg.ini";
    if (!saveToIni(config, iniPath)) {
        return false;
    }

    // Save extra/CSP config if enabled
    if (config.enableCsp) {
        saveExtraConfig(config, serverPath);
    }

    return true;
}

bool ServerConfigEditor::loadFromIni(ServerConfig& config, const QString& iniPath) {
    QFile file(iniPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    QString currentSection;

    while (!stream.atEnd()) {
        QString line = stream.readLine().trimmed();

        // Skip comments and empty lines
        if (line.startsWith(';') || line.startsWith('#') || line.isEmpty()) {
            continue;
        }

        // Section header
        if (line.startsWith('[') && line.endsWith(']')) {
            currentSection = line.mid(1, line.length() - 2);
            continue;
        }

        // Key-value pair
        if (line.contains('=')) {
            int eqPos = line.indexOf('=');
            QString key = line.left(eqPos).trimmed();
            QString value = line.mid(eqPos + 1).trimmed();

            // Parse based on key name
            if (key == "NAME") config.name = value;
            else if (key == "DESCRIPTION") config.description = value;
            else if (key == "PASSWORD") config.password = value;
            else if (key == "ADMIN_PASSWORD") config.adminPassword = value;
            else if (key == "IP") config.ip = value;
            else if (key == "PORT") config.port = value.toInt();
            else if (key == "HTTP_PORT") config.httpPort = value.toInt();
            else if (key == "MAX_CLIENTS") config.maxClients = value.toInt();
            else if (key == "SLOT_COUNT") config.slotCount = value.toInt();
            else if (key == "TRACK") config.track = value.toInt();
            else if (key == "CONFIG_TRACK") config.trackConfig = value;
            else if (key == "SESSION_TYPE") config.sessionType = value.toInt();
            else if (key == "SESSION_DURATION") config.sessionDuration = value.toInt();
            else if (key == "LAPS_COUNT") config.lapsCount = value.toInt();
            else if (key == "WAIT_TIME") config.waitTime = value.toInt();
            else if (key == "WEATHER") config.weather = value;
            else if (key == "TIME_OF_DAY") config.timeOfDay = value.toFloat();
            else if (key == "SUN_ANGLE") config.sunAngle = value.toFloat();
            else if (key == "USE_REAL_WEATHER") config.useRealWeather = (value == "1");
            else if (key == "TIME_MULTIPLIER") config.timeMultiplier = value.toInt();
            else if (key == "GRIP") config.gripModifier = value.toFloat();
            else if (key == "DYNAMIC_TRACK") config.dynamicTrack = (value == "1");
            else if (key == "TRACK_CONDITIONS") config.trackConditions = value.toInt();
            else if (key == "IS_LOCKED") config.isLocked = (value == "1");
            else if (key == "ALLOW_AUTOPILOT") config.allowAutopilot = (value == "1");
            else if (key == "ALLOW_VIRTUAL_MIRROR") config.allowVirtualMirror = (value == "1");
            else if (key == "MAX_BALLAST") config.maxBallast = value.toInt();
            else if (key == "DUMP_INTERVAL") config.dumpInterval = value.toInt();
        }
    }

    file.close();
    return true;
}

bool ServerConfigEditor::saveToIni(const ServerConfig& config, const QString& iniPath) {
    QFile file(iniPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    stream << EditorConfig::instance().serverConfigHeader();
    stream << "; Generated by ksEditor\n\n";

    stream << "[SERVER]\n";
    stream << "NAME=" << config.name << "\n";
    stream << "DESCRIPTION=" << config.description << "\n";
    stream << "PASSWORD=" << config.password << "\n";
    stream << "ADMIN_PASSWORD=" << config.adminPassword << "\n";
    stream << "IP=" << config.ip << "\n";
    stream << "PORT=" << config.port << "\n";
    stream << "HTTP_PORT=" << config.httpPort << "\n";
    stream << "MAX_CLIENTS=" << config.maxClients << "\n";
    stream << "SLOT_COUNT=" << config.slotCount << "\n\n";

    stream << "[TRACK]\n";
    stream << "TRACK=" << config.track << "\n";
    stream << "CONFIG_TRACK=" << config.trackConfig << "\n";
    stream << "DYNAMIC_TRACK=" << (config.dynamicTrack ? "1" : "0") << "\n";
    stream << "TRACK_CONDITIONS=" << config.trackConditions << "\n";
    stream << "GRIP=" << QString::number(config.gripModifier, 'f', 2) << "\n\n";

    stream << "[SESSION]\n";
    stream << "SESSION_TYPE=" << config.sessionType << "\n";
    stream << "SESSION_DURATION=" << config.sessionDuration << "\n";
    stream << "LAPS_COUNT=" << config.lapsCount << "\n";
    stream << "WAIT_TIME=" << config.waitTime << "\n\n";

    stream << "[WEATHER]\n";
    stream << "WEATHER=" << config.weather << "\n";
    stream << "TIME_OF_DAY=" << QString::number(config.timeOfDay, 'f', 2) << "\n";
    stream << "SUN_ANGLE=" << QString::number(config.sunAngle, 'f', 2) << "\n";
    stream << "USE_REAL_WEATHER=" << (config.useRealWeather ? "1" : "0") << "\n";
    stream << "TIME_MULTIPLIER=" << config.timeMultiplier << "\n\n";

    stream << "[RULES]\n";
    stream << "IS_LOCKED=" << (config.isLocked ? "1" : "0") << "\n";
    stream << "ALLOW_AUTOPILOT=" << (config.allowAutopilot ? "1" : "0") << "\n";
    stream << "ALLOW_VIRTUAL_MIRROR=" << (config.allowVirtualMirror ? "1" : "0") << "\n";
    stream << "MAX_BALLAST=" << config.maxBallast << "\n";
    stream << "DUMP_INTERVAL=" << config.dumpInterval << "\n";

    file.close();
    return true;
}

// ============================================================================
// Entry list operations
// ============================================================================

QVector<ServerConfigEditor::EntryInfo> ServerConfigEditor::loadEntryList(const QString& serverPath) {
    QVector<EntryInfo> entries;

    QString entryPath = serverPath + "/cfg/entry_list.ini";
    QFile file(entryPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return entries;
    }

    QTextStream stream(&file);
    EntryInfo currentEntry;
    bool inEntry = false;

    while (!stream.atEnd()) {
        QString line = stream.readLine().trimmed();

        // Skip comments and empty lines
        if (line.startsWith(';') || line.startsWith('#') || line.isEmpty()) {
            continue;
        }

        // Section header
        if (line.startsWith('[') && line.endsWith(']')) {
            // Save previous entry
            if (inEntry && !currentEntry.guid.isEmpty()) {
                entries.append(currentEntry);
            }

            QString section = line.mid(1, line.length() - 2);
            inEntry = section.startsWith("CAR_");

            if (inEntry) {
                currentEntry = EntryInfo();
            }
            continue;
        }

        // Key-value pair
        if (inEntry && line.contains('=')) {
            int eqPos = line.indexOf('=');
            QString key = line.left(eqPos).trimmed();
            QString value = line.mid(eqPos + 1).trimmed();

            if (key == "DRIVERNAME") currentEntry.name = value;
            else if (key == "TEAM") currentEntry.team = value;
            else if (key == "GUID") currentEntry.guid = value;
            else if (key == "MODEL") currentEntry.carModel = value;
            else if (key == "SKIN") currentEntry.skin = value;
            else if (key == "SPECTATOR_MODE") currentEntry.spectatorMode = value.toInt();
            else if (key == "BALLAST") currentEntry.ballast = value.toInt();
            else if (key == "RESTRICTOR") currentEntry.restrictor = value.toInt();
        }
    }

    // Save last entry
    if (inEntry && !currentEntry.guid.isEmpty()) {
        entries.append(currentEntry);
    }

    file.close();
    return entries;
}

bool ServerConfigEditor::saveEntryList(const QVector<EntryInfo>& entries, const QString& serverPath) {
    QString entryPath = serverPath + "/cfg/entry_list.ini";
    QFile file(entryPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    stream << EditorConfig::instance().serverEntryListHeader();
    stream << "; Generated by ksEditor\n\n";

    for (int i = 0; i < entries.size(); ++i) {
        stream << "[CAR_" << i << "]\n";
        stream << formatEntryLine(entries[i]) << "\n\n";
    }

    file.close();
    return true;
}

bool ServerConfigEditor::addEntry(const EntryInfo& entry, const QString& serverPath) {
    QVector<EntryInfo> entries = loadEntryList(serverPath);
    entries.append(entry);
    return saveEntryList(entries, serverPath);
}

bool ServerConfigEditor::removeEntry(const QString& guid, const QString& serverPath) {
    QVector<EntryInfo> entries = loadEntryList(serverPath);

    for (int i = entries.size() - 1; i >= 0; --i) {
        if (entries[i].guid == guid) {
            entries.remove(i);
        }
    }

    return saveEntryList(entries, serverPath);
}

bool ServerConfigEditor::updateEntry(const EntryInfo& entry, const QString& serverPath) {
    QVector<EntryInfo> entries = loadEntryList(serverPath);

    for (int i = 0; i < entries.size(); ++i) {
        if (entries[i].guid == entry.guid) {
            entries[i] = entry;
            return saveEntryList(entries, serverPath);
        }
    }

    return false;
}

// ============================================================================
// CSP/Extra config
// ============================================================================

bool ServerConfigEditor::loadExtraConfig(ServerConfig& config, const QString& serverPath) {
    QString extraPath = serverPath + "/cfg/extra_cfg.yml";
    QFile file(extraPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    QString content = stream.readAll();
    file.close();

    // Parse YAML-like format
    QRegularExpression kvRegex("^(\\w[\\w\\s]*):\\s*(.+)$");
    QStringList lines = content.split('\n');

    for (const QString& line : lines) {
        QString trimmed = line.trimmed();
        if (trimmed.startsWith('#')) continue;

        QRegularExpressionMatch match = kvRegex.match(trimmed);
        if (match.hasMatch()) {
            QString key = match.captured(1).trimmed();
            QString value = match.captured(2).trimmed();

            config.cspSettings[key] = value;

            if (key == "ENABLE_CSP") {
                config.enableCsp = (value == "1" || value.toLower() == "true");
            } else if (key == "CSP_VERSION") {
                config.cspVersion = value;
            }
        }
    }

    return true;
}

bool ServerConfigEditor::saveExtraConfig(const ServerConfig& config, const QString& serverPath) {
    QString extraPath = serverPath + "/cfg/extra_cfg.yml";
    QFile file(extraPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream stream(&file);
    stream << "# CSP Extra Configuration\n";
    stream << "# Generated by ksEditor\n\n";

    stream << "ENABLE_CSP: " << (config.enableCsp ? "1" : "0") << "\n";

    if (!config.cspVersion.isEmpty()) {
        stream << "CSP_VERSION: " << config.cspVersion << "\n";
    }

    // Write other CSP settings
    for (auto it = config.cspSettings.begin(); it != config.cspSettings.end(); ++it) {
        if (it.key() != "ENABLE_CSP" && it.key() != "CSP_VERSION") {
            stream << it.key() << ": " << it.value() << "\n";
        }
    }

    file.close();
    return true;
}

// ============================================================================
// Presets
// ============================================================================

ServerConfigEditor::ServerConfig ServerConfigEditor::getPresetSprint() {
    ServerConfig config;
    config.name = "Sprint Race";
    config.description = "Quick sprint race session";
    config.sessionType = 2;
    config.sessionDuration = 300;
    config.lapsCount = 5;
    config.waitTime = 10;
    config.maxClients = 16;
    return config;
}

ServerConfigEditor::ServerConfig ServerConfigEditor::getPresetEndurance() {
    ServerConfig config;
    config.name = "Endurance Race";
    config.description = "Long endurance race";
    config.sessionType = 2;
    config.sessionDuration = 3600;
    config.lapsCount = 0;
    config.waitTime = 30;
    config.maxClients = 30;
    return config;
}

ServerConfigEditor::ServerConfig ServerConfigEditor::getPresetDrift() {
    ServerConfig config;
    config.name = "Drift Session";
    config.description = "Free drift practice";
    config.sessionType = 0;
    config.sessionDuration = 1800;
    config.lapsCount = 0;
    config.waitTime = 5;
    config.maxClients = 8;
    config.allowAutopilot = false;
    return config;
}

ServerConfigEditor::ServerConfig ServerConfigEditor::getPresetCruise() {
    ServerConfig config;
    config.name = "Cruise Session";
    config.description = "Casual cruise session";
    config.sessionType = 0;
    config.sessionDuration = 7200;
    config.lapsCount = 0;
    config.waitTime = 0;
    config.maxClients = 20;
    config.allowVirtualMirror = true;
    return config;
}

// ============================================================================
// Validation
// ============================================================================

bool ServerConfigEditor::validateConfig(const ServerConfig& config, QString* error) {
    if (config.name.isEmpty()) {
        if (error) *error = "Server name is empty";
        return false;
    }

    if (config.port < 1024 || config.port > 65535) {
        if (error) *error = "Invalid port number";
        return false;
    }

    if (config.maxClients < 1 || config.maxClients > 100) {
        if (error) *error = "Invalid max clients (1-100)";
        return false;
    }

    if (config.sessionDuration < 60) {
        if (error) *error = "Session duration too short (minimum 60 seconds)";
        return false;
    }

    return true;
}

bool ServerConfigEditor::validateEntryList(const QVector<EntryInfo>& entries, QString* error) {
    QStringList guids;

    for (const EntryInfo& entry : entries) {
        if (entry.guid.isEmpty()) {
            if (error) *error = "Entry missing GUID";
            return false;
        }

        if (entry.carModel.isEmpty()) {
            if (error) *error = "Entry missing car model: " + entry.name;
            return false;
        }

        if (guids.contains(entry.guid)) {
            if (error) *error = "Duplicate GUID: " + entry.guid;
            return false;
        }

        guids.append(entry.guid);
    }

    return true;
}

// ============================================================================
// Utility
// ============================================================================

QString ServerConfigEditor::getSessionTypeName(int type) {
    switch (type) {
        case 0: return "Practice";
        case 1: return "Qualifying";
        case 2: return "Race";
        default: return "Unknown";
    }
}

QString ServerConfigEditor::getWeatherName(const QString& weatherId) {
    static QMap<QString, QString> weatherNames;
    if (weatherNames.isEmpty()) {
        weatherNames["clear_01"] = "Clear";
        weatherNames["cloudy_01"] = "Cloudy";
        weatherNames["light_rain_01"] = "Light Rain";
        weatherNames["heavy_rain_01"] = "Heavy Rain";
        weatherNames["storm_01"] = "Storm";
        weatherNames["fog_01"] = "Fog";
    }
    return weatherNames.value(weatherId, weatherId);
}

QStringList ServerConfigEditor::getAvailableTracks(const QString& contentPath) {
    QStringList tracks;

    QDir tracksDir(contentPath + "/tracks");
    if (tracksDir.exists()) {
        QFileInfoList dirs = tracksDir.entryInfoList(QDir::Dirs | QDir::NoDotAndDotDot);
        for (const QFileInfo& dirInfo : dirs) {
            tracks.append(dirInfo.fileName());
        }
    }

    return tracks;
}

QStringList ServerConfigEditor::getAvailableCars(const QString& contentPath) {
    QStringList cars;

    QDir carsDir(contentPath + "/cars");
    if (carsDir.exists()) {
        QFileInfoList dirs = carsDir.entryInfoList(QDir::Dirs | QDir::NoDotAndDotDot);
        for (const QFileInfo& dirInfo : dirs) {
            cars.append(dirInfo.fileName());
        }
    }

    return cars;
}

// ============================================================================
// Private helpers
// ============================================================================

bool ServerConfigEditor::parseEntryLine(const QString& line, EntryInfo& entry) {
    if (!line.contains('=')) return false;

    int eqPos = line.indexOf('=');
    QString key = line.left(eqPos).trimmed();
    QString value = line.mid(eqPos + 1).trimmed();

    if (key == "DRIVERNAME") entry.name = value;
    else if (key == "TEAM") entry.team = value;
    else if (key == "GUID") entry.guid = value;
    else if (key == "MODEL") entry.carModel = value;
    else if (key == "SKIN") entry.skin = value;
    else if (key == "SPECTATOR_MODE") entry.spectatorMode = value.toInt();
    else if (key == "BALLAST") entry.ballast = value.toInt();
    else if (key == "RESTRICTOR") entry.restrictor = value.toInt();
    else return false;

    return true;
}

QString ServerConfigEditor::formatEntryLine(const EntryInfo& entry) {
    QString result;
    result += "DRIVERNAME=" + entry.name + "\n";
    result += "TEAM=" + entry.team + "\n";
    result += "GUID=" + entry.guid + "\n";
    result += "MODEL=" + entry.carModel + "\n";
    result += "SKIN=" + entry.skin + "\n";
    result += "SPECTATOR_MODE=" + QString::number(entry.spectatorMode) + "\n";
    result += "BALLAST=" + QString::number(entry.ballast) + "\n";
    result += "RESTRICTOR=" + QString::number(entry.restrictor);
    return result;
}
